### ISSUE TITLE
Regels m.b.t. organische stofgehalteklasse onjuist

### ISSUE THREAD

**Issue by ArthurDeMoel** [BROprogramma/BHR-GT#10]
In paragraaf 9.3.8 (attribuut organische stofgehalteklasse pag. 107/108) van de BRO-catalogus staat bij 
Regels:
Het gegeven ontbreekt wanneer de waarde van het attribuut grondsoort gelijk is aan _detritus, zwakZandigeDetritus, matigzandigeDetritus, sterkZandigeDetritus, siltigeDetritus, kleiigeDetritus, humus, zwakZandigeHumus, matigZandigeHumus, sterkZandigeHumus, siltigeHumus, kleiigeHumus, veen, zwakZandigVeen, matigzandigVeen, sterkZandigVeen, siltigVeen, kleiigVeen, bruinkool of gyttja_. **In andere gevallen is het gegeven aanwezig.**

Dit impliceert dat wanneer er geen sprake is van voornamelijk organische grond, dat het attribuut organische stofgehalteklasse altijd aanwezig moet zijn. Aangezien de 'kleinste' variant van dit attribuut de waarde 'zwakOrganisch' heeft, zou dit betekenen dat elke niet organische grondsoort (zoals zand, klei, silt) altijd minimaal zwak organisch zou zijn. Dit is onjuist.

Oplossing: dit attribuut optioneel maken en niet verplicht in het geval van 'andere gevallen' zoals nu beschreven in de regels. Andere optie is aan de codelijst de waarde 'nietOrganisch' toe te voegen, alhoewel dit niet de voorkeur geniet.

**Comment by fterpstra** [comment]
In versie 0.9 opgelost
