### ISSUE TITLE
Afgewerktinterval.aanvulmateriaal onterecht verplicht?

### ISSUE THREAD

**Issue by RLHuisman** [BROprogramma/BHR-GT#109]
## Type issue
Publieke consultatie

## Waar
20181221 Booronderzoek - Geotechnische boormonsteranalyse en Geotechnische boormonsterbeschrijving.pdf
'Paragraaf 3. Domeintabel', 'pagina 312'.]

## Samenvatting
Afgewerktinterval.aanvulMateriaal
Waarom is dit veld verplicht? er is niet altijd aanvul materiaal. Bijv in een situatie met een stalen buis als afwerking.

## Oplossingsrichting
Maak dit veld optioneel

**Comment by RuudMutsaers** [comment]
De domeinwaarden geven ruimte om ook die aspecten te vangen.
