### ISSUE TITLE
Velden die van het type IndicatieJaNee zijn verplicht

### ISSUE THREAD

**Issue by RLHuisman** [BROprogramma/BHR-GT#110]
## Type issue
Publieke consultatie

## Waar
20181221 Booronderzoek - Geotechnische boormonsteranalyse en Geotechnische boormonsterbeschrijving.pdf
'Paragraaf 3 het domeinmodel', 'pagina 312'

## Samenvatting
Heel veel velden die van het type IndicatieJaNee zijn verplicht, alleen veel van deze velden worden in het veld niet vastgelegd of digitaal geregistreerd. Moet dit dan ook aangeleverd worden in het aanleverings betand? 
Want dit kan dan nog wel een probleem worden in de uitwisseling. Want als het niet vastgelegd is, is er ook geen default waarde als bijv. Onbekend.

## Oplossingsrichting
Optioneel maken, of van type JaNeeOnbekend.

**Comment by RuudMutsaers** [comment]
Het gaat hier over het borgen van de informatie. Met betrokkenen is besproken welke aspecten van belang zijn om te weten. Het goed benoemen van de betreffende aspecten is onderdeel van de afspraak. Als een dergelijk attribuut in de software als default kan worden ingevuld, en natuurlijk op waarheid is berust dan is dat geen probleem. Als er verschil zit tussen de werkwijze per boring zal dit inderdaad per boring benoemd moeten worden.
