### ISSUE TITLE
Booronderzoek geen project

### ISSUE THREAD

**Issue by RLHuisman** [BROprogramma/BHR-GT#111]
## Type issue
Publieke consultatie

## Waar
20181221 Booronderzoek - Geotechnische boormonsteranalyse en Geotechnische boormonsterbeschrijving.pdf
'Paragraaf 3 het domeinmodel', 'pagina 312'

## Samenvatting
Als ik het goed lees, wordt er per boring een booronderzoek aan geleverd en niet op project basis?
Hierdoor moeten veel gegevens bij ieder meetpunt meegegeven gaan worden met veel redundante informatie, bijvoorbeeld terreintoestand, is dat gewenst?

**Comment by RuudMutsaers** [comment]
De BRO is gebaseerd op hergebruik. In het kader van hergebruik kan elk object afzonderlijk worden gebruikt en dient alle informatie bij dat object aanwezig te zijn. Indien dat informatie is die project gerelateerd is en dus voor meerdere objecten geld betekend dat inderdaad dat die informatie meerder malen aanwezig is in de BRO maar telkens bij een object omdat dat voor dat object relevant is.
