### ISSUE TITLE
Laagbeschijvingen vs Sliblaag en Geboord interval

### ISSUE THREAD

**Issue by RLHuisman** [BROprogramma/BHR-GT#112]
## Type issue
Publieke consultatie

## Waar
20181221 Booronderzoek - Geotechnische boormonsteranalyse en Geotechnische boormonsterbeschrijving.pdf
'Paragraaf 3 het domeinmodel', 'pagina 312'

## Samenvatting
Gegevens zoals Sliblaag en geboord interval worden in de praktijk vaak als lagen vastgelegd met beide gegevens in 1 laag. Op deze manier komen dus vaak dezelfde trajecten terug. Is dit gewenst?
De gegevens komen later dus ook nog als lagen terug, zoals beschreven op pagina: 313. Welke data wordt dan vervolgens leidend? De laagbeschrijving of de gegevens in Sliblaag en Geboord interval?

**Comment by RuudMutsaers** [comment]
De informatie betreft 2 afzonderlijke aspecten waarvan de dieptes mogelijk overeenkomen. echter is dit niet noodzakelijk vandaar dat de aspecten afzonderlijk worden vastgelegd.
