### ISSUE TITLE
NEN14688

### ISSUE THREAD

**Issue by RLHuisman** [BROprogramma/BHR-GT#113]
## Type issue
Publieke consultatie

## Waar
20181221 Booronderzoek - Geotechnische boormonsteranalyse en Geotechnische boormonsterbeschrijving.pdf
'Paragraaf 3 het domeinmodel', 'pagina 313'

## Samenvatting
Moeten alle keuzes voor de NEN14688 apart vastgelegd worden, of alleen de conclusie die eruit komt?
Dit is belangrijk voor de inwinning, als alle losse keuzes vastgelegd moeten worden. Dan moet dit wel vastgelegd gaan worden tijdens het boren door de veldwerkers.

**Comment by RuudMutsaers** [comment]
Voor het gehele booronderzoek moeten naast de aspecten die volgens NEN-EN-ISO 14688 moeten worden benoemd ook nog andere aspecten benoemd worden zoals de informatie van de boring en de bemonstering. De catalogus geeft een overzicht van alle aspecten die vastgelegd moeten worden.
