### ISSUE TITLE
Uitwisselmodel vs domeinmodel

### ISSUE THREAD

**Issue by RLHuisman** [BROprogramma/BHR-GT#114]
## Type issue
Publieke consultatie

## Waar
20181221 Booronderzoek - Geotechnische boormonsteranalyse en Geotechnische boormonsterbeschrijving.pdf
'Paragraaf 3 het domeinmodel', 'pagina 312'

## Samenvatting
Het domeinmodel is een beschrijving van de ideale wereld. Komt hier nog een slag overheen voor een uitwisselformaat waarbij objecten/entiteiten generieker worden opgelost? 
Zodat er nog nagedacht wordt over een uitwisselformaat wat niet bij elke minimale wijziging tot een nieuwe versie leidt?

**Comment by RuudMutsaers** [comment]
Vooralsnog geeft de catalogus weer wat voor dat moment met de stakeholders is afgesproken. Vervolgens zal het geheel in beheer genomen worden. Vanuit beheer zal gekeken worden hoe met veranderingen om te gaan en op welke wijze deze doorgevoerd kunnen worden.
