### ISSUE TITLE
Procesafspraken toekomstige aanpassingen gegevensdefinitie

### ISSUE THREAD

**Issue by skapinga** [BROprogramma/BHR-GT#115]
## Type issue
Publieke consultatie

## Waar
Pag. 299

“Het accent ligt op standaard geotechnisch booronderzoek. Wat dat inhoudt is in de gegevensdefinitie vastgelegd. Uitgangspunt daarbij is dat de informatie in de basisregistratie ondergrond alleen betrekking heeft op boringen die verticaal bedoeld zijn. Gegevens die niet onder het standaard onderzoek vallen zijn niet opgenomen. Wanneer de grenzen verlegd worden, en dat zal in de toekomst zeker gebeuren, zal de gegevensdefinitie moeten worden aangepast.”

## Samenvatting
Bovenstaande tekst levert veel vragen op over het vervolg

## Vragen
Volgens welke (proces)afspraken zal de gegevensdefinitie worden aangepast als dat gebeurt? Op wiens initiatief gebeurt dat?
Op welke manier is in het datamodel rekening gehouden met mogelijke toekomstige aanpassingen?
Zijn mogelijke toekomstige aanpassingen aan de gegevensdefinitie nu al in beeld?

**Comment by RuudMutsaers** [comment]
De procedure omtrent wensen, onvolkomenheden en aanpassingen wordt momenteel uitgewerkt. Een en ander heeft te maken met het feit dat BRO wetgeving betreft en dat dit ook juridische afstemming vergt. Indien de procedure is uitgewerkt zal dit ook kenbaar gemaakt worden.
