### ISSUE TITLE
Samenhang NEN 5104 en NEN 14688

### ISSUE THREAD

**Issue by skapinga** [BROprogramma/BHR-GT#116]
## Type issue
Publieke consultatie

## Waar
Pag. 302

“Onder NEN 5104 worden minder gegevens vastgelegd, is de samenhang minder strikt geborgd en kan de betekenis van gegevens anders zijn. Sommige gegevens kunnen alleen bestaan onder NEN 5104, andere gegevens kunnen juist niet bestaan onder die norm. Een ander verschil is dat de nieuwe methode een strikt onderscheid maakt tussen gegevens die uit het beschrijven en de gegevens die uit het meten voortkomen. In het verleden was dat niet het geval en als gevolg is niet altijd duidelijk waarop de gegevens van een oude beschrijving berusten.”

## Vraag
Is er een verschilanalyse van deze gegevens publiekelijk beschikbaar?

**Comment by RuudMutsaers** [comment]
Vanuit de nieuwe norm is duidelijk waarop de gegevens berust zijn en hoe die tot stand gekomen zijn. dit is inderdaad vanuit het verleden niet altijd helder. Het is bij de BRO niet bekend of er vanuit de productie of gebruikerskant van de geotechnische branche een verschilanalyse beschikbaar is.
