### ISSUE TITLE
NEN 5104 en BRO vanaf 2020

### ISSUE THREAD

**Issue by skapinga** [BROprogramma/BHR-GT#117]
## Type issue
Publieke consultatie/Review sessie [verwijderen wat niet van toepassing is]

## Waar
Pag. 302

“Overigens valt een boormonsterbeschrijving die onder NEN 5104 tot stand is gekomen per definitie onder booronderzoek met kwaliteitsregime IMBRO/A.”

## Vraag
Is het ook mogelijk om boringen die na 2020 zijn uitgevoerd en (na opname van boormonsterbeschrijving in de BRO) volgens de NEN 5104 zijn beschreven als IMBRO/A op te nemen in de basisregistratie?

**Comment by RuudMutsaers** [comment]
Wanneer de contracten zijn afgesloten voor 1-1-2020 is het toegestaan om booronderzoeken die uitgevoerd zijn tot 1-1-2023 aan te leveren in IMBRO/A. Men is echter wel verplicht om doorlopende contracten waaronder ook na 1-1-2023 geotechnisch booronderzoek wordt uitgevoerd, te herzien zodat men IMBRO kwaliteit gaat aanleveren.
