### ISSUE TITLE
aanleveren boormonsteranalyses

### ISSUE THREAD

**Issue by skapinga** [BROprogramma/BHR-GT#118]
## Type issue
Publieke consultatie

## Waar
Pag. 302 – 303

“Er is maar een geval waarin er geen werkzaamheden in het veld worden uitgevoerd en dat is wanneer booronderzoek gebruik maakt van de resultaten uit eerder veldwerk of uit veldwerk dat voor een andere opdrachtgever is uitgevoerd.”

## Vraag
Kunnen boormonsterbeschrijvingen en boormonsteranalyses separaat worden aangeleverd aan de BRO? Zo ja, Op welke wijze wordt de beschrijving en de analyse aan elkaar gekoppeld?
In vervolg op bovenstaande vraag: is het mogelijk om boormonsteranalyses die voor 2020 zijn uitgevoerd aan te leveren aan de BRO? Zo ja, onder welk regime? Wat gebeurt er als de boormonsterbeschrijving al in het DINO database is opgenomen?

## Oplossingsrichting
Voor de bruikbaarheid van de BRO is het mijn wens om eerder uitgevoerde boormonsteranalyses op te nemen in de voorziening.

**Comment by RuudMutsaers** [comment]
Dit issue wordt opgepakt bij de aanlevering van de brondocumenten. Hiervoor is een omschrijving in de maak.
