### ISSUE TITLE
samengesteld boorprofiel bij verschillende bemonsteringswijzen

### ISSUE THREAD

**Issue by skapinga** [BROprogramma/BHR-GT#119]
## Type issue
Publieke consultatie

## Waar
Pag. 304:
“De intervallen die niet beschreven konden worden, worden expliciet in het profiel opgenomen (Niet-beschreven interval) en de reden daarvoor wordt vastgelegd.”

## Vraag
Op welke wijze manier wordt hier mee omgegaan met boringen die zijn uitgevoerd volgens het principe van “continue gestoken monstername”?

## Waar
Pag. 305:
“Een geval waarin een boormonsterbeschrijving NEN-EN-ISO 14688-1 twee boorprofielen oplevert is wanneer op een bepaalde plaats een boring is gezet die op twee manieren bemonsterd is.”

## Samenvatting
Deze alinea stelt dat er meerdere discontinue boorprofielen nodig zijn vanwege een verschil in kwaliteit van de monstername en beschrijving (verkennend). Biedt het datamodel mogelijkheden om een samengesteld boorprofiel te maken zoals dat nu gebruikelijk is? Zo ja, hoe?
Bovenstaande vraag wordt ook gesteld in het geval er een boormonsteranalyse op is uitgevoerd (pag 307).

## Oplossingsrichting
Wens is om een samengesteld boorprofiel weer te kunnen geven op basis van deze catalogus

**Comment by RuudMutsaers** [comment]
Het datamodel borgt alle informatie die geproduceerd wordt. Als het wenselijk is om daar een synthese profiel van te maken die deze informatie bij elkaar brengt zou dit vanuit gebruikerssoftware moeten worden gefaciliteerd.
