### ISSUE TITLE
Verschillende catalogussen

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#12]
P1.2, alinea 3: (HvM)
Het mag hier explicieter worden beschreven waarom er twee catalogussen zijn voor 1 registratieobject. Waarom kan dat niet worden gecombineerd? Wanneer volgens catalogus1 en wanneer volgens catalogus2 aanleveren? Kan het voorkomen dat je voor beide catalogussen moet aanleveren?

**Comment by fterpstra** [comment]
Het combineren de twee catalogi staat bij de open punten in de inleiding benoemd als "Harmonisatie tussen de bodemkundige en geotechnische boormonsterbeschrijving" . Het combineren kan pas wanneer we de catalogi af hebben en een volgende versie van de eerdere catalogus gaan maken. Dit gaat zeker niet op korte termijn gebeuren. Tot die tijd kan het zeker voorkomen dat je aan beide catalogi moet aanleveren.
