### ISSUE TITLE
Codelijst 39. GeotechnischeAfzettingskarakteristiek

### ISSUE THREAD

**Issue by skapinga** [BROprogramma/BHR-GT#120]
## Type issue
Publieke consultatie

## Waar
Pag. 250
39. GeotechnischeAfzettingskarakteristiek

## Vraag
Wat is de relatie van deze code lijst met geologische eenheden, modelbenamingen van GeoTop en ook de eenheden beschreven in het stochastische ondergrond schematisatie?

## Oplossingsrichting
Wens is om de karakteristiek van een bepaalde laag te koppelen aan bestaande geologische eenheden en andere modelmatige interpretaties.

**Comment by RuudMutsaers** [comment]
Deze relatie zou moeten ontstaan bij het maken van de modellen.
