### ISSUE TITLE
Afgeleide paramaters bepaling van de verticale vervorming

### ISSUE THREAD

**Issue by skapinga** [BROprogramma/BHR-GT#121]
## Type issue
Publieke consultatie

## Waar
pag 308

## Samenvatting
In de huidige adviespraktijk worden uit een samendrukkingsproef een aantal parameters gerapporteerd die niet zijn beschreven in de concept gegevens catalogus. Dit zijn onder andere

- Initiële void ratio
- Gewicht monster
- Volumegewicht
- Watergehalte voor en na de proef. (is het mogelijk om 2 keer een watergehalte aan 1 proefstuk te koppelen?)
- Uitwerking van de proef volgens verschillende methoden (o.a. isotachen, Koppejan, Casagrande)
- Grensspanning
- Indicatie van terreinspanning

Op welke manier is voorzien dat deze parameters wel uitgewisseld kunnen worden in het IMBRO formaat en passen in het domeinmodel. Zonder uitwerking van de proef met bovenstaande is de toegevoegde waarde van een uniforme uitwisseling erg klein omdat er dan meerdere gegevensstromen voor 1 proef nodig zijn, nl. 1 voor de BRO en 1 voor de aanvullende parameters Bovendien zijn schaduwarchieven noodzakelijk die qua vorm en structuur verschillen.
Is het een mogelijkheid om deze niet authentieke parameters wel op te nemen in het datamodel en alleen beschikbaar te stellen aan de bronhouders?

**Comment by RuudMutsaers** [comment]
In sommige gevallen worden bepaalde analyses op hetzelfde monster uitgevoerd. alle informatie die dus noodzakelijk is om een bepaalde analyse te interpreteren zou dus aanwezig moeten zijn. Wanneer5 bepaalde aspecten als input worden ingeschat geldt dat die ook geregistreerd dienen te worden.
