### ISSUE TITLE
Droge volumieke massa

### ISSUE THREAD

**Issue by skapinga** [BROprogramma/BHR-GT#122]
## Type issue
Publieke consultatie

## Waar
2.21 Bepaling van de volumieke massa

## Vraag
Is het ook mogelijk om het droge volumewicht op te nemen in de structuur van de huidige gegevenscatalogus? (ook in relatie tot het geotechnische watergehalte?) Zo ja, hoe?

**Comment by RuudMutsaers** [comment]
Dit is een andere analyse te weten volumieke massa vaste delen.
