### ISSUE TITLE
Afgeleide parameters volumieke massa

### ISSUE THREAD

**Issue by skapinga** [BROprogramma/BHR-GT#123]
## Type issue
Publieke consultatie

## Waar
2.21 Bepaling van de volumieke massa
3 Het domeinmodel

## Samenvatting
Afgeleide parameters op basis van volumieke massa, watergehalte en volumieke massa vaste delen
Een aantal afgeleide parameters zoals porositeit, poriengetal, verzadigingsgraad en verzadigd volumegewicht zijn niet beschreven in de gegevenscatalogus, maar worden in de dagelijkse adviespraktijk wel gevraagd en veel gebruikt. Deze parameters hebben een 1 op 1 relatie met de parameters die wel zijn opgenomen in de catalogus. Waarom worden deze parameters niet toegevoegd aan de catalogus?

**Comment by RuudMutsaers** [comment]
Alle analyses worden apart uitgewerkt en opgenomen in de BRO. Er moeten echter wel keuzes gemaakt worden in het kader van prioritering. Bij het prioriteren wordt zoveel mogelijk rekening gehouden met de samenhang van de analyses.
