### ISSUE TITLE
Inschatting van de volumieke massa van vaste delen

### ISSUE THREAD

**Issue by skapinga** [BROprogramma/BHR-GT#124]
## Type issue
Publieke consultatie/Review sessie [verwijderen wat niet van toepassing is]

## Waar
2.22 Bepaling van de volumieke massa vaste delen

## Samenvatting
In de dagelijkse praktijk wordt veel gebruik gemaakt van bestaande of specifieke relaties om de volumieke massa van de vaste delen in te schatten, bijvoorbeeld om afgeleide parameters te bepalen. Is het een mogelijkheid om deze niet authentieke parameter wel op te nemen in het datamodel en alleen beschikbaar te stellen aan de bronhouders? 

## Beschrijving
[Lange omschrijving van de melding. Probeer zo concreet mogelijk het probleem of je suggestie voor verbetering te beschrijven. Bijvoorbeeld: 'Het is onduidelijk wat er precies met ... bedoeld wordt'.]

## Oplossingsrichting
[Geef een suggestie voor een oplossing, in de vorm van een tekstvoorstel of een oplossingsrichting.]

**Comment by RuudMutsaers** [comment]
In de BRO worden in principe allen gegevens opgenomen en geen interpretaties. Indien er een procedure is die altijd op identieke wijze wordt uitgevoerd kan dit opgenomen worden in de BRO aangezien dat voor iedereen gelijkwaardige informatie is. 

Inschattingen die als aanname voor een analyse gemaakt zijn worden als input bij een analyse opgeslagen.
