### ISSUE TITLE
Beheer en volledigheid 9. codelijst bepalingsprocedure

### ISSUE THREAD

**Issue by skapinga** [BROprogramma/BHR-GT#125]
## Type issue
Publieke consultatie/Review sessie [verwijderen wat niet van toepassing is]

## Waar
Pag. 216
9. Bepalingsprocedure Waarde IMBRO

## Samenvatting
In deze codelijst zijn alleen actuele procedures beschreven. Op welke manier wordt in de toekomst deze codelijst beheerd? Wat moeten gebruikers doen om nieuwe bepalingsprocedures toe te voegen aan de code lijst? Welke eisen zijn er dan?
Moeten voorheen gebruikte procedures niet worden opgenomen in IMBRO/A om ook eerder uitgevoerde proeven op te nemen in de database?

**Comment by RuudMutsaers** [comment]
Voor de boormonsteranalyses wordt momenteel alleen afgesproken wat we voor de toekomst uitwisselen. Dat betekend dat we niet terug hoeven te kijken naar methodes en procedures uit het verleden. 
Indien er in de toekomst andere procedures en methodes ontwikkeld worden waarvoor de gegevens set niet toereikend is zal dit indien wenselijk moeten worden opgepakt zodat de BRO daar op wordt aangepast. de procedure hieromtrent wordt momenteel uitgewerkt.
