### ISSUE TITLE
Textuur organische grond voor QM5 (geroerd)

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#127]
## Type issue
Opmerking uit implementatie

## Melding
Tabel NA.2 uit de norm stelt dat bij de bepaling van Veentextuur de minimale monsterkwaliteit QM4 moet zijn. Dus in het geval van een geroerd monster (QM5) zou die niet bepaald hoeven/mogen worden. Lijkt mij dus dat in de BRO bij dit attribuut opgenomen moet worden dat in het geval van beschrijfkwaliteit klasse2geroerd (of bemonsteringskwaliteit klasseE) het attribuut niet aanwezig is.
## Beoordeling
Mogelijk betekent dit ook voor de norm dat hier in de tabel een aanpassing nodig is. Het is nu zwart wit wat betekent het is er wel of niet maar mogelijk is er ook nog een grijs gebied.

## Betrekking op
Norm en catalogus

## Workaround
Vanuit de Norm wordt het benoemen van de veentextuur niet afgedwongen in het geval van monsterkwaliteit QM5. De BRO doet dit wel. Workaround: Norm op dit vlak negeren en Veentextuur altijd benoemen. Indien het niet vast te stellen is te beneomen als "amorf".

**Comment by RuudMutsaers** [comment]
Dit wordt opgelost in een volgende versie van de catalogus

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
