### ISSUE TITLE
Primaire en secundaire fractie organische gronden / monsterkwaliteit

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#129]
## Type issue
Opmerking uit implementatie

## Melding
Volgens dezelfde tabel (NA.2)  kan de primaire fractie en de secundaire fractie van organische grond niet bepaald worden in het geval van een geroerd monster. Heel bijzonder.
## Beoordeling
Het bepalen van de verschillende fracties kan ongeacht de monsterkwaliteit plaatsvinden aangezien het gaat over de samenstelling. Dit zou een omissie in de tabel van de norm zijn. Doorgeven dat dit aangepast moet worden in de tabel. Het is wel opgenomen in de grondsoortnaam binnen de BRO.
## Betrekking op
Norm 

## Workaround
Vanuit de Norm wordt het benoemen van de primaire en secundaire fractie  van organische gronden niet afgedwongen in het geval van monsterkwaliteit QM5. De BRO doet dit wel. Workaround: Norm op dit vlak negeren en fracties altijd te benoemen.

**Comment by RuudMutsaers** [comment]
wordt aangepast in de norm

**Comment by BregjeBrugman** [comment]
is inmiddels aangepast in norm NEN-EN-ISO 14688-1:2019+NEN8890:2020
