### ISSUE TITLE
Gebruik gegevens

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#13]
P2.9 alinea 3:
Opnemen "Disclaimer" dat gegevens  dienen te worden geinterperteerd en gebruikt door een deskundige.

**Comment by fterpstra** [comment]
Hartelijk dank voor de suggestie, we nemen deze disclaimer echter niet op.
Deze paragraaf gaat over wat een "authentiek gegeven" is en de betreffende allinea over correctheid. Wanneer gegevens door een niet deskundige worden gebruikt zijn de gegevens zelf nog steeds correct. De interpretatie en het gebruik kunnen inderdaad verkeerd zijn, maar dat doet niets af aan de authentiek zijn van de gegevens. Een disclaimer verzwakt alleen maar de betekenis van authentiek gegeven, je kan dan bijvoorbeeld claimen de authentieke gegevens niet te hoeven gebruiken omdat je niet deskundig bent of geen deskundige kan vinden.
