### ISSUE TITLE
kalkgehalteklasse niet voor QM5 (geroerd)

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#131]
## Type issue
Opmerking uit implementatie

## Melding
Minimale vereiste monsterkwaliteit voor bepaling kalkgehalte is bij fijne grond QM4, bij grove grond QM5. Is dit bewust gedaan?

## Gerelateerd issue
#132 kalkgehalteklasse bij organische en zeer grove gronden
#136 klasse-indeling van kalkgehalteklasse
#226 schrijffout in regel bij kalkgehalteklasse
#227 kalkgehalteklasse onder klasse 3
#228 kalkgehalteklasse onder IMBRO/A
#243 kalkgehalteklasse onder klasse 3 (keuzevrijheid)

## Beoordeling
Het bepalen van het kalkgehalte kan zowel aan gestoken als geroerd materiaal plaatsvinden. Daarbij is geen verschil tussen fijne en grove grond. Voor beide gevallen zou dus moeten gelden dat het ook voor QM5 geld. Doorgeven aan de norm dat dit aangepast dient te worden.  

## Betrekking op
Norm 

## Workaround
Vanuit de Norm wordt het bij een beschrijfkwaliteit 2 het bepalen van het kalkgehalte bij fijne gronden niet afgedwongen in het geval van monsterkwaliteit QM5. De BRO doet dit wel. Workaround: Norm op dit vlak negeren en kalkgehalte altijd te benoemen.

**Comment by RuudMutsaers** [comment]
Besproken met norm, Wordt in nieuwe catalogus opgepakt

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
