### ISSUE TITLE
kalkgehalteklasse niet bij organische en zeer grove gronden

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#132]
## Type issue
Opmerking uit implementatie

## Melding
Bij organische grond en zeer grove grond hoeft kalkgehalte niet bepaald te worden, terwijl kalkgehalte in de BRO catalogus altijd verplicht is (behalve bij klasse 3 beschrijving). Gaarne dit aanpassen.

## Gerelateerd issue
#131 kalkgehalteklasse bij monsterkwaliteit QM5
#136 klasse-indeling van kalkgehalteklasse
#226 schrijffout in regel bij kalkgehalteklasse
#227 kalkgehalteklasse onder klasse 3
#228 kalkgehalteklasse onder IMBRO/A
#243 kalkgehalteklasse onder klasse 3 (keuzevrijheid)

## Beoordeling
Het klopt dat de norm zegt dat je dat bij organische grond en zeer grove grond niet bepaald. Navragen of dit (altijd) klopt en indien dat het geval is kan er op twee manieren geschakeld worden. De eerste methode is om een regel toe te voegen waarbij aangegeven wordt dat het bij die gevallen niet aangegeven dient te worden, of de domeinwaarde toevoegen niet bepaald die alleen in die gevallen ingevuld mag worden. In het laatste geval heeft men de mogelijkheid om het toch in te vullen als men het wel heeft bepaald. 

## Betrekking op
Norm en catalogus

## Workaround
Vanuit de Norm wordt het bepalen van het kalkgehalte bij organische en zeer grove grond voor beschrijfkwaliteit 2  niet afgedwongen. De BRO doet dit wel. Workaround: Norm op dit vlak negeren en bij beschrijfkwaliteit 2 altijd te benoemen ongeacht monsterkwaliteit.

**Comment by RuudMutsaers** [comment]
Wordt opgelost in nieuwe versie catalogus

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
