### ISSUE TITLE
beschrijving Korrelvorm

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#133]
## Type issue
Opmerking uit implementatie

## Melding
13.	6.1.2 Korrelvorm
Bij grind, keitjes en keien behoort de korrelvorm te worden beschreven aan de hand van de hoekigheid van de deeltjes (de mate van afronding aan de randen en hoeken), hun globale vorm en hun oppervlaktekenmerken. Tabel 3 geeft een overzicht van termen die hiervoor worden gebruikt. Het is gebruikelijk dat de gemiddelde hoekigheid of afronding aan de hand van standaardoverzichten wordt geschat.

Hier wordt niet over zand gesproken. In de BRO-catalogus staat dat de korrelvorm wel degelijk beschreven moet worden als de primaire fractie zand is (behalve de korrelruwheid dan).

Hier wordt gesteld dat bij zand en grind alleen de korrelhoekigheid bepaald moet worden. Volgens de BRO-catalogus moet voor grind (in welke hoedanigheid dan ook) en (primaire fractie) zand ook de korrelsfericiteit beschreven worden en voor grind ook de korrelruwheid.
N.B. In het gedeelte voor zeer grove grond (keien, keitjes) in dezelfde tabel staan deze vereiste kenmerken wel vermeld, hetgeen overeenkomt met de BRO-catalogus.

Wat is nu correct, de BRO-catalogus of de norm ? Oftewel, wat wordt de instructie voor boormonsterbeschrijvers in het veld en het lab als het om bovenstaande gaat ?
## Beoordeling
Opmerking m.b.t. de Norm: In de tabel NA.2 is bij grove grond (zand) alleen aangegeven dat de korrelhoekigheid moet worden benoemd voor klasse 2. Bij zeer grove grond (grind keitjes en keien) moet bij klasse 2 de korrelhoekigheid, de korrelruwheid en de korrelsfericiteit benoemd worden. Echter bij de omschrijving NA.2.4.4. staat bij de opmerking dat de oppervlakkteruwheid voor grind twee klasse heeft, echter zou dit moeten zijn voor de zeer grove fractie. 

Er wordt in de norm gesproken over grove minerale korrels (NA.2.4.4.) en grind, keitjes en keien (6.1.2.). Daarbij wordt niets aangegeven over van welke fractie je dat moet benoemen (primair, secundair of tertiair). Het feit dat het niet benoemd wordt kan aangeven dat het van alle fracties moet, echter is dat niet duidelijk. In de tabel NA.2 is dit niet expliciet gemaakt maar wordt de suggestie gewekt dat dit alleen voor de primaire fractie geld. In de BRO geld het voor alle fracties zand, grind, keitjes en keien de kogelvorm bepaald dient te worden ongeacht de primaire primaire fractie. daarbij is wel benoemd dat er een maximum van 2 facties is waarvan men dit kan benoemen. 

Voor klasse 3 geld dat zowel voor grove als zeer grove grond niets benoemd wordt. Dit komt overeen met de regel die beschreven staat in de catalogus.
## Betrekking op
Norm en catalogus

## Workaround
Vanuit de Nom wordt binnen klasse 2 het benoemen van de korrelvorm per fractie niet altijd afgedwongen. De BRO doet dit wel. Workaround: Norm op dit vlak negeren en korrelvorm altijd te benoemen. Dit geld voor de fracties zand, grind, keitjes en keien en zowel voor de primaire als de secundaire fractie en in het geval van grind ook de tertiaire fractie.

**Comment by RuudMutsaers** [comment]
De essentie van de korrelvorm is dat men de krorrelvorm benoemd van het materiaal wat bepalend is voor het gedrag. Bij het benoemen van de geotechnische grondsoort is de keuze van de naamgeving ook gebaseerd op het feit dat het materiaal wat bepalend is voor het gedrag in de naamgeving wordt opgenomen. Je kunt dus eigenlijk zeggen dat je van de fracties die in de naam zitten ook de korrelvorm moet benoemen.

**Comment by RuudMutsaers** [comment]
Overleg met normcommissie besproken.
Korrelvorm geldt alleen van de hoofdfractie wordt in zowel norm als nieuwe catalogus opgepakt

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
