### ISSUE TITLE
Grindmediaanklasse (Grond) alleen voor primaire fractie

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#134]
## Type issue
Opmerking uit implementatie

## Melding
Op pagina 15 van de norm 14688-1 staat bij de voetnoot:

* Nederlandse voetnoot: In Nederland worden de nadere kenmerken van een secundaire fractie niet vermeld:
– in plaats van zandig GRIND: sterk of zwak zandig (fijn, middelmatig, grof) GRIND;
– in plaats van grofzandig fijn GRIND: sterk of zwak zandig fijn GRIND;
– in plaats van middelgrof zandig SILT: sterk of zwak zandig SILT;
– in plaats van fijn grindig, siltig grof ZAND: siltig ZAND met veel/weinig grind of sterk of zwak grindig
ZAND;–
– in plaats van sterk siltig fijn ZAND: siltig fijn ZAND
– in plaats van fijn grindig, grofzandig SILT: sterk of zwak zandig SILT met veel/weinig grind of sterk of zwak
grindig SILT;
– in plaats van fijn zwak middelgrof

Als voorbeeld de in rood gedrukte omschrijving. De grindmediaan wordt in Nederland dus niet vermeld. Maar hoe moet ik hier het woord ‘vermeld’ interpreteren? Als je het niet vermeldt dan komt het mijns inziens er op neer dat je hem ook niet hoeft te bepalen, want wat heeft het anders voor zin. Dit komt in principe ook overeen met de opmerking b) op pagina 51 van de norm:

Voor een Klasse 2‐beschrijving wordt voor zand en grind als primaire fractie minimaal
een indeling in grof, middelgrof of fijn gemaakt op basis van respectievelijk de zand‐ of de grindmediaan.

Dit suggereert ook dat je het alleen voor de primaire fractie hoeft te doen. Echter de BRO-catalogus stelt dat de grindmediaanklasse bepaald moet worden indien de grond grind bevat (in welke vorm dan ook), dus ook bij zwakGrindigZand, sterkGrindigZand. 
Dit is dus met elkaar in tegenspraak.

## Gerelateerd issue
#224 grindmediaanklasse (Onderzocht materiaal) alleen voor primaire fractie

## Beoordeling
Er is onderscheid tussen de mediaan en de mediaanklasse. Voor 14688 deel 1 geld dat de mediaan nooit bepaald wordt. In tabel NA.2 staat aangegeven dat voor grove gronden de mediaan korrelfractie op subfractieniveua wordt aangegeven. Dit zou betekenen dat bij zand zowel de mediaanklasse van zand als van grind opgegeven moet worden. Dat geld zowel voor klasse 2 als 3. 
## Betrekking op
Norm en catalogus

## Workaround
Vanuit de Nom wordt binnen klasse 2 het benoemen van de korrelvorm per fractie niet altijd afgedwongen. De BRO doet dit wel. Workaround: Norm op dit vlak negeren en altijd korrelfractie benoemen. Dit geld voor de fracties zand en grind waarbij het op een zo gedetailleerd mogelijk niveau (Nederlandse verbijzondering) benoem moet worden.

**Comment by RuudMutsaers** [comment]
Wordt opgepakt in nieuwe catalogus

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
