### ISSUE TITLE
Naamgeving Standaardblauw in norm

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#135]
## Type issue
Opmerking uit implementatie

## Melding
In de norm wordt gesproken over Blauw. In de BRO over standaard blauw

De NEN 14688 hanteert tabel 5  (blauw en blauwachtig)
De NA hanteert tabel NA13 (lichtblauw,blauw,donkerblauw)
De Bro heeft tabel 55(standaardblauw, lichtblauw en donkerblauw)
## Beoordeling
Het klopt inderdaad dat bij de norm een typefout is gemaakt in de NA. Alle andere kleuren zijn aangegeven met standaard behalve bij blauw is dat mis gegaan. Ik zou inderdaad adviseren om daar gewoon standaardBlauw voor te hanteren!
## Betrekking op
Norm 

## Workaround
Naamgevingen norm en BRO komen niet overeen. Workaround: Technische vertaling maken in de software zodat de naamgevingen goed verwerkt worden in het uitwisselformaat.

**Comment by RuudMutsaers** [comment]
Wordt aangepast in de Norm

**Comment by BregjeBrugman** [comment]
In NEN-EN-ISO 14688-1:2019+NEN8990 is de term standaardBlauw opgenomen.
