### ISSUE TITLE
Domeinwaarde kalkgehalteklasse 

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#136]
## Type issue
Opmerking uit implementatie

## Melding
1- Kalkgehalteklasse
Bro-tabel 54:
Bro heeft er 3 en de 14688 heeft er 4 
(-Zwakkalkhoudend ontbreekt in de BRO)

## Gerelateerd issue
#131 kalkgehalteklasse bij monsterkwaliteit QM5
#132 kalkgehalteklasse bij organische en zeer grove gronden
#226 schrijffout in regel bij kalkgehalteklasse
#227 kalkgehalteklasse onder klasse 3
#228 kalkgehalteklasse onder IMBRO/A
#243 kalkgehalteklasse onder klasse 3 (keuzevrijheid)

## Beoordeling
Er is een verschil tussen de norm en de BRO. Het blijkt dat dit een punt is dat aan het eind van de totstandkoming van de norm veranderd is maar niet is terug gekoppeld aan de BRO. De dit moet dus veranderd worden in de BRO. 
## Betrekking op
Norm en catalogus

## Workaround
De domeinwaarde van de norm en de BRO wijken af. Workaround: Waarde "zwak kalkhoudend" uit de norm  vertalen  naar "kalkhoudend" in de BRO.

**Comment by RuudMutsaers** [comment]
Vierdeling van de norm wordt opgenomen in de BRO

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
