### ISSUE TITLE
Disperse inhomogeniteit

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#137]
## Type issue
Opmerking uit implementatie

## Melding
5-Disperse inhomogeniteiten
BRO-tabel 31
BRO heeft er 31 , 14688 heeft er 10
## Beoordeling
Norm is niet volledig
## Betrekking op
Norm
## Workaround
De domeinwaarde van de norm en de BRO wijken af. Workaround: Waarde van de BRO aanhouden.

**Comment by RuudMutsaers** [comment]
In de norm wordt een betere verwijzing opgenomen naar de BRO

**Comment by BregjeBrugman** [comment]
Lijst in de norm is informatief met verwijzing naar de BRO: "Disperse inhomogeniteiten (deze lijst is niet uitputtend, verwezen wordt naar BRO)". bron: NEN-EN-ISO 14688-1:2019+NEN8890:2020
