### ISSUE TITLE
Naamgeving domeinwaarde DisperseInhomogeniteit

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#138]
## Type issue
Opmerking uit implementatie

## Melding
De naamgeving is niet gelijk 
-grindlensjesVeel versus grindlezenVeel?
-kleibrokjesVeel versus kleibrokkenVeel?
## Beoordeling
Dit is niet wenselijk maar kan technisch worden opgelost.
## Betrekking op
Norm
## Workaround
Naamgevingen norm en BRO komen niet overeen. Workaround: Technische vertaling maken in de software zodat de naamgevingen goed verwerkt worden in het uitwisselformaat.

**Comment by RuudMutsaers** [comment]
Norm gaat dit aanpassen

**Comment by BregjeBrugman** [comment]
Inmiddels (BHR-GT versie 1.99 en NEN-EN-ISO 14688 + NEN8990 2020) wel gelijk; brokjes
