### ISSUE TITLE
Onderverdeling in de BRO van  "Pseudo-vezelig" uit norm 

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#139]
## Type issue
Opmerking uit implementatie

## Melding
7-TextuurOrganische grond-Veentextuur?
BRO-tabel 80
BRO heeft er 8 (5 imbro en 14688 heeft er 4)
(pseudo-vezelig versus grofPseudovezelig en fijnPseudovezelig)

## Gerelateerd issue
#147 (= duplicaat)

## Beoordeling
In de norm wordt er geen onderscheid gemaakt tussen fijn en grof bij pseudovezelig. 
## Betrekking op
Norm en catalogus
## Workaround
De domeinwaarde van de norm en de BRO wijken af. Workaround: Afwijking van de norm bij pseudo-vezelig ook een grofte aangegeven.

**Comment by RLHuisman** [comment]
Ik denk dat de workaround niet helemaal werkbaar is, dit betekend dat bij het invoeren inderdaad moet worden afgeweken van de norm. Dit lijkt me niet helemaal netjes toch? Waarom wijkt de BRO af van de norm?
Wie gaat dit opleiden/uitleggen aan de medewerkers die dit invoeren, in de norm staat niet uitgelegd wanneer het bijv. grof of fijn pseudo-vezelig is. Hoe gaat hier op worden gehandhaafd?

De norm kent de volgende opties:
Veentextuur | Code
-- | --
Amorf | fibn
Fijnvezelig | fibf
Grofvezelig | fibc
pseudo-vezelig | fibp

In praktijk:
Stel er is bijv pseudo-vezelig ingevuld: hoe kunnen we die mappen aan een grof of fijn pseudovezelig in de BRO?

**Comment by RuudMutsaers** [comment]
De workaround is een tijdelijke oplossing aangezien er een discrepantie is tussen hetgeen wat met experts is afgesproken en opgenomen is in de BRO en wat uiteindelijk in de norm is opgenomen. Er moeten afspraken gemaakt worden met de normcommissie over wat nu daadwerkelijk wenselijk is. De tijdelijke workaround is bedoeld voor de ketentest die momenteel loopt. De intentie is om hier zo snel mogelijk duidelijkheid met de normcommissie over te hebben.

**Comment by RuudMutsaers** [comment]
Zie ook 147 Norm heft de ogelijkheid om grofte aanduiding mee te geven. In de nieuwe cartalogus wordt de waarde ook zonder grofte aanduiding toegestaan.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
