### ISSUE TITLE
Eigen locaties vijf registratieobjecten

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#14]
P3.1 alinea 4:
Met het oog op een voorboring hoeft dit niet zo te zijn! Hierbij uitgaande dat met locaties (RD en NAP) worden bedoeld.

**Comment by fterpstra** [comment]
Antwoord Robert-Jan van Leeuwen
De voorboring is een begrip dat voor veel verwarring zorgt. Wanneer in een project een verkennende boring wordt gedaan en kort daarna op precies dezelfde plek een tweede boring, is er sprake van een booronderzoek met een locatie.  Wordt de tweede boring op een andere plek gemaakt dan is er sprake van twee booronderzoeken. Wordt er tbv een sondeerzoek een verkennende boring gemaakt die niet precies op dezelfde plek staat als de sondering, dan ontstaan er en een booronderzoek en een sondeeronderzoek. Is het wel op dezelfde plaats dan is er sprake van "voorboren"in het sondeeronderzoek.
