### ISSUE TITLE
Uitleg gelaagdheid / gelaagde inhomogeniteit / disperse inhomogeniteit

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#142]
## Type issue
Opmerking uit implementatie
## Melding
In de NEN-EN-IS0 14688-1 wordt bij de gelaagdheid (NA 2.3.1) eigenlijk alleen maar gesproken over samengestelde lagen, dus wat in de BRO gelaagde inhomogeniteit heet. Ik vind in de norm niet duidelijk iets terug over een 'gelaagde' laag die uit hetzelfde materiaal bestaat, terwijl in de BRO het attribuut 'gelaagdheid' juist alleen betrekking heeft op een NIET samengestelde laag. Ook al begrijp ik de opzet en het is het wellicht niet fout, kan ik me voorstellen dat als iemand de norm en de BRO catalogus naast elkaar legt, dat het verwarrend overkomt.
## Betrekking op
Catalogus
## Reactie standaardisatie
Gelaagdheid is op diverse wijze te onderscheiden en wordt dus ook op diverse wijze vastgelegd. De onduidelijkheid die hier wordt aangegeven geeft aan dat er behoefte is aan uitleg van dit issue in de catalogus.

**Comment by BregjeBrugman** [comment]
gekoppeld aan #285

**Comment by BregjeBrugman** [comment]
De BRO is aangepast, gelaagdheid wordt nu ook vastgelegd van samengestelde lagen. De aanpassing is vastgelegd in werkafspraak versie 2.1, zie werkafsprakenlijst nr.12
https://bro-productomgeving.nl/bpo/latest/bodem-en-grondonderzoek/booronderzoek-bhr/geotechnisch-booronderzoek-bhr-gt/werkafspraak-geotechnisch-booronderzoek-tranche-3
