### ISSUE TITLE
Geotechnische grondsoort en Textuur organische grond

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#147]
## Type issue
Opmerking uit implementatie

## Melding
In tabel 80 TextuurOrganische Grond zijn de organisch grondsoorten anders benoemd:
VEEN, vezelig,grof
VEEN, vezelig fijn
VEEN, PseudoVezelig, fijn
VEEN, PseudoVezelig, grof
VEEN, amorf
## Betrekking op
Catalogus

## Gerelateerd issue
is al geregistreerd onder #139 

## Reactie standaardisatie
Het betreft hier een combinatie van geotechnische grondsoort en textuurorganische grond. voor de texttuur geld dat het onderstaande domeinwaarde zijn.  
amorf 
fijnPseudoVezelig
fijnVezelig
grofPseudoVezelig
grofVezelig

Voor IMBRO/A zijn er nog een paar andere mogelijkheden.

**Comment by RLHuisman** [comment]
Waarom kent de BRO fijn en grof Pseudo vezelig? De iso/NEN 14688-1 geeft alleen deze opties:

Veentextuur | Code
-- | --
Amorf | fibn
Fijnvezelig | fibf
Grofvezelig | fibc
pseudo-vezelig | fibp

**Comment by RuudMutsaers** [comment]
Vanuit de norm kan men bij pseudo-vezelig er voor keizen om ook de grofte aan te geven. Wordt in volgende catalogus verwerkt zodat men ook zonder grofte aanduiding kan aanleveren.

**Comment by RLHuisman** [comment]
Hoi Ruud,
op basis van de ISO 14688-1 kan dit als het goed is niet:
"Vanuit de norm kan men bij pseudo-vezelig er voor keizen om ook de grofte aan te geven. "
In de norm zijn deze 4 opties beschreven:

Veentextuur | Code
-- | --
Amorf | fibn
Fijnvezelig | fibf
Grofvezelig | fibc
pseudo-vezelig | fibp

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
