### ISSUE TITLE
Korrelvorm en groottefracties

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#156]
## Type issue
Opmerking uit implementatie
## Melding
bij de korrelvorm kan men 4 groottefracties aangeven terwijl er maar maximaal 2 aangeleverd kunnen worden.
## Betrekking op
Catalogus
## Reactie standaardisatie
Uitleg bij de entiteit waarom men maximaal 2 fracties kan benoemen en hoe die uitwerking is.

**Comment by RuudMutsaers** [comment]
Vanuit de Norm is aangegeven dat de korrelvorm allen van de hoofdfractie wordt aangegeven. Dit punt wordt aangepast in zowel de norm als in de nieuwe catalogus.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
