### ISSUE TITLE
Domeinwaarde bijzonder bestanddeel

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#157]
## Type issue
Opmerking uit implementatie
## Melding
Ik wil toch nog even terugkomen op mijn laatste ingezonden constatering m.b.t. de bijzondere bestanddelen.
Daar bleek voor bijvoorbeeld hout en de plantenrestenNietHoutig in de norm een Veel en Weinig variant is en in de BRO-tabel niet (nog even los van het feit dat hout in de BRO-catalogus houtGebruikt heet).
## Betrekking op
Norm en Catalogus
## Reactie standaardisatie
In de omschrijving staat aangegeven waarom er veel of weinig aangegeven dient te worden: "Een bestanddeel dat uit materiaal bestaat dat niet tot een grondsoort wordt gerekend en niet bepalend is voor de geotechnische eigenschappen van de grond met, wanneer relevant, aanduiding van de relatieve hoeveelheid ervan."
In de norm is een kleine opsomming gemaakt van de domeinwaarde. Echter is een verwijzing naar de BRO opgenomen en aangegeven dat de BRO leidend is. Mogelijk is dit wel verwarrend aangezien het niet duidelijk aangegeven is in de norm dat dat voorbeelden zijn.

**Comment by RuudMutsaers** [comment]
Bij de lijst met mogelijkheden in de norm wordt een verwijzing opgenomen naar de BRO aangezien de BRO de complete lijst domeinwaarde heft.

**Comment by BregjeBrugman** [comment]
De BRO is aangepast, plantenrestenHoutig en plantenrestenNietHoutig hebben nu ook een aanduiding Veel en Weinig. De aanpassing is vastgelegd in werkafspraak versie 2.1, zie werkafsprakenlijst nr.10
https://bro-productomgeving.nl/bpo/latest/bodem-en-grondonderzoek/booronderzoek-bhr/geotechnisch-booronderzoek-bhr-gt/werkafspraak-geotechnisch-booronderzoek-tranche-3
