### ISSUE TITLE
Consistentie fijne grond / monsterkwaliteit

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#158]
## Type issue
Opmerking uit implementatie

## Melding
Tabel NA.2 uit de norm stelt dat bij de bepaling van de consistentie van fijne grond de minimale monsterkwaliteit QM4 moet zijn. Dus in het geval van een geroerd monster (QM5) zou die niet bepaald hoeven/mogen worden. Lijkt mij dus dat in de BRO bij dit attribuut opgenomen moet worden dat in het geval van beschrijfkwaliteit klasse2geroerd (of bemonsteringskwaliteit klasseE) het attribuut niet aanwezig is.

## Gerelateerd issue
#223 consistentie fijne grond niet verplicht voor klasse 3
#225 schrijffout in regel bij consistentie fijne grond

## Beoordeling
Dit punt is besproken met de experts. Zij hebben aangegeven dat de consistentie ook van fijne grond ook in sommige gevallen bepaald kan worden aan de hand van geroerd materiaal. Echter denk ik dat Arthur gelijk heeft dat dit niet in alle gevallen kan, en dat dit momenteel door de norm niet afgedwongen wordt. Het betekent dat hier naar gekeken moet worden en dat het voor geroerd materiaal niet verplicht gesteld moet worden.

Mogelijk betekent dit ook voor de norm dat hier in de tabel een aanpassing nodig is. Het is nu zwart wit wat betekent het is er wel of niet maar mogelijk is er ook nog een grijs gebied.  
## Betrekking op
Norm 

## Workaround
Vanuit de Norm wordt het benoemen van de consistentie van fijne gronden niet afgedwongen in het geval van monsterkwaliteit QM5. De BRO doet dit wel. Workaround: Norm op dit vlak negeren en consistentie van fijne gronden altijd benoemen. Indien het niet vast te stellen is te benoemen als "zeerSlap".

**Comment by RuudMutsaers** [comment]
In overleg met norm wordt dit opgepakt in volgende catalogus.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
