### ISSUE TITLE
sterkZandigeKleiMetGrind is niet mogelijk toch?

### ISSUE THREAD

**Issue by RLHuisman** [BROprogramma/BHR-GT#159]
hoe kunnen jullie op deze komen volgens de ISO 14688?

GeotechnischeGrondsoort | urn:bro:bhrgt:GeotechnicalSoilName | sterkZandigeKleiMetGrind | Ja | Ja | Fijne minerale   grond die zich gedraagt als klei, goed zichtbaar en duidelijk voelbaar zand   en enkele grindkorrels bevat.
-- | -- | -- | -- | -- | --

Eerst beschrijf je een Primaire; dat wordt Klei. 
Dan beschrijf je een Secundaite, dat wordt Zwak Zandig
De beschrijf je een Tertiary, dat mag bestaan uit:
schelpfragmenten, glauconietkorrels, ijzersulfiden,
plantenresten en wortelresten, kalkhoudende of andere concreties

Dan zou grindig toch een BijzonderBestanddeel zijn en niet de grondsoort?

**Comment by RuudMutsaers** [comment]
Zie in de norm onder tabel NA.12 pagina 53 de opmerking:

OPMERKING 1 Er is in principe maar één secundaire fractie. Een bijmenging van grind wordt altijd
vermeld., omdat deze visueel te onderscheiden is. De percentages voor de geschatte massadelen
van grove grond zijn indicatief.

In dit geval wordt dus ook "met grind" toegevoegd aan de grondsoortnaam.
