### ISSUE TITLE
analyseren vs beproeven

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#16]
Pagina 23 van 182 alinea 1:
zinsdeel: "....het veelal in een laboratorium analyseren van monsters..."

Wordt "beproeven" ook onder analyseren verstaan?

**Comment by fterpstra** [comment]
Inderdaad beproeven wordt hier onder verstaan, is een nuttige aanvullling welke meegenomen is in versie 0.9
