### ISSUE TITLE
scheefstaand

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#160]
## Type issue
Opmerking uit implementatie

## Melding
validatie bro-bhr-gt: klasse2 ongeroerd: waarom is veld scheefstaand een verplicht veld?, idem voor bijzondermateriaal. Dat staat niet in de nen14688. Wat heeft dit te maken met een geroerd monster? Bij klasse 3 of 2geroerd wordt beschrijving wel als valide beoordeeld. De grondsoort is toch niet afhankelijk van het feit of een monster geroerd, of ongeroerd
## Beoordeling
Met experts is afgesproken dat scheefstaand een verplichting is om te vermelden. Dit is inderdaad niet in de Norm terecht gekomen. Dit zal voorgelegd worden aan de normcommissie. 
Scheefstand is alleen bij ongeroerd materiaal te herkennen. Vandaar dat het alleen daar benoemd moet worden.
## Betrekking op
Norm en catalogus

## Oplossingsrichting
aanpassing regel, scheefstaand verplicht wanneer interne structuur intact (QM1-3) en optioneel voor klasse 3 (via interne structuur intact).

**Comment by RuudMutsaers** [comment]
In overleg met norm is er een voorstel wat wordt uitgewerkt in volgende catalogus

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
