### ISSUE TITLE
schrijffout in regel bij Korrelvorm, consistentie fijne grond en grindmediaanklasse (zwakGrindigSilt en sterkGrindigSilt)

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#161]
## Type issue
Opmerking uit implementatie

## Melding
Validatie BHR-gt: consistentie fijne grond: In de nen14688 wordt gesproken over Silt,zwak grindig en de naam volgens de BRO is dat zwakGrindigSilt. Maar in de regels voor de validatie volgens de BRO catalogus, pagina 103 (10.3.25) staat zwakgrindigeSilt. grindig versus grindige. Daar loopt de validatie op fout. Wat is juist? De validator(regels volgens Bro-catalogus) of de nen14688?
## Beoordeling
In de norm staat omschreven dat de schrijfwijze is als "zwakGrindigSilt" In de calatogus  in de domeinwaardelijst als staat hetzelfde maar in de regels bij Grindmediaanklasse, consistentie fijne grond, korrelvorm en grindmediaanklasse staat het omschreven als "zwakGrindigeSilt".  dit geld ook voor Sterk grindig silt.
Controle vind nu plaats op de verkeerde naamgeving en wordt dus niet goed uitgevoerd.
## Betrekking op
Catalogus

**Comment by RuudMutsaers** [comment]
Punt wordt opgelost in volgende catalogus

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
