### ISSUE TITLE
Beworteld in norm niet verplicht

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#162]
## Type issue
Opmerking uit implementatie

## Melding
Vraag over een Validatieregel:
Waarom is bij een grondsoortbeschrijving het veld (beworteld) rooted verplicht? Zonder dit veld wordt het xml niet goedgekeurd.
In de nen14688 wordt dat niet vereist.
Wanneer je een boring tot 100 m zet moet je nu bij elke laag bij de grondsoort dit veld zetten. Dan krijg je dat er in de software dit veld standaard op nee wordt gezet. Ik verwacht niet namelijk niet dat een veldwerker blij wordt wanneer ie dat veld dit bij elke laag moet aangeven met (ja of nee). Is dat wat de bro wil?

## Beoordeling
Tijdens het standaardisatietraject is met experts overeengokomen dat bewordteld van belang was om te benoemen. Het is uiteindelijk niet in de norm  benoemd als attribuut. Afstemming met experts en Norm of dit wel toegevoegd moet worden.
## Betrekking op
Norm en Catalogus
## Workaround
Attribuut dient altijd aanwezig te zijn zoals aangegeven in de catalogus.

**Comment by RuudMutsaers** [comment]
Vanuit de norm is aangegeven dat men dit toch niet van belang vindt. Attribuut komt te vervallen in volgende versie van catalogus

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
