### ISSUE TITLE
Monstervochtigheid bij beschrijving in het veld

### ISSUE THREAD

**Issue by RuudMutsaers** [BROprogramma/BHR-GT#163]
## Type issue
Opmerking uit implementatie

## Melding
Monstervochtigheid mag alleen aanwezig zijn wanneer beschrijflocatie lab is. Bij beschrijflocatie veld mag het niet aanwezig zijn. In de nen14688 staat dat je dat moet vastleggen ten tijde van het beschrijven. De validatieregel van de BRO is in tegenspraak met de 14688

## Beoordeling
Volgens de Norm dient men de vochtigheidstoestand van het monster altijd te beschrijven. In de catalogus is de regel toegevoegd dat dit alleen opgegeven dient te worden wanneer de beschijflocatie lab is. 
Afstemmen met experts en Norm of benoeming voor veldbeschrijving ook noodzakelijk/wenselijk is.
## Betrekking op
Norm en Catalogus
## Workaround
Bij veldbeschrijving voorlopig vochtigheidstoestand achterwegen laten

**Comment by RuudMutsaers** [comment]
Dit wordt opgelost in de nieuwe catalogus. Monstervochtigheid zal altijd moeten worden opgegeven

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
