### ISSUE TITLE
Type poreuze stenen bij TX proef toevoegen

### ISSUE THREAD

**Issue by HarryBRO** [BROprogramma/BHR-GT#168]
## Type issue
Publieke consultatie

## Waar
Paragraaf 3.39

## Samenvatting
Type poreuze steen als variabele opnemen

## Beschrijving
Het gebruikte type poreuze steen kan invloed hebben op het resultaat, deze ontbreekt

## Oplossingsrichting
Type poreuze stenen toevoegen:
Poreuze stenen
Gladde eindplaten

**Comment by fterpstra** [comment]
ogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_booronderzoek_geotechische_boormonsterbeschrijving_en_boormonsteranalyse_v0_99_docx.pdf voor de resulterende catalogus.

**Comment by HarryBRO** [comment]
Beste Frank,

Bij het aanklikken van de link in onderstaande mail, wordt de catalogus Booronderzoek geologische boormonsterbeschrijving gedownload, terwijl de geotechnische catalogus in de link staat beschreven. Kan dat gewijzigd worden?

Met vriendelijke groet,
Harry van Essen

**Comment by fterpstra** [comment]
We zijn er mee bezig

Frank Terpstra
+31657469506
(Sent from my iPhone)

**Comment by fterpstra** [comment]
De goede link is https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf
