### ISSUE TITLE
attribuut proefstuk verstoord Zettingseigenschappen

### ISSUE THREAD

**Issue by JPietersen** [BROprogramma/BHR-GT#169]
## Type issue
Review sessie

## Waar
3.32.7 maximaal spanningsverschil & 3.32.8 maximaal rekverschil
(Bepaling zettingseigenschappen - Verzadigingsfase)

## Samenvatting
Attribuut waarnaar verwezen wordt bestaat niet/heet anders

## Beschrijving
In de Regels van bovenstaande attributen wordt verwezen naar het attribuut 'proefstuk verstoord', terwijl deze niet voorkomt onder de Verzadigingsfase. Waarschijnlijk moet de naam van het attribuut waarnaar verwezen wordt 'verstoring opgetreden' zijn.

## Oplossingsrichting
In Regels onder 3.32.7 en 3.32.8 vervangen van 'proefstuk verstoord' door 'verstoring opgetreden'.

**Comment by fterpstra** [comment]
ogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
