### ISSUE TITLE
beschrijving van monster

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#17]
Pagina 27 van 182 alinea 2:
zinsdeel: "Het deelonderzoek dat bijna altijd wordt uitgevoerd is het beschrijven van de boormonsters en..."

Wordt hierbij specifiek de "veldbeschrijving" bedoeld?
- Zo ja, waarom dan ook niet noemen zoals het bedoeld word?
- Zo niet, dan beter duiden dat meer optie mogelijk zijn door bijvoorbeeld het benoemen van voorbeelden.

**Comment by fterpstra** [comment]
het gaat om beschrijven ongeacht de plaats waar dat plaatsvindt. Bij het invullen van sectie 3.6 "geotechnisch booronderzoek" is hier in versie 0.9 meer duidelijkheid over gegeven.
