### ISSUE TITLE
schrijffout in regel bij Korrelvorm (klasse2geroerd en klasse2ongeroerd)

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/BHR-GT#170]
## Type issue
Review sessie

## Waar
3.23, korrelvorm

## Samenvatting
Hoofdletters gebruikt bij referenties naar codelijstwaarden

## Beschrijving
`De entiteit moet aanwezig zijn wanneer de waarde van het attribuut beschrijfkwaliteit van de entiteit Boorprofiel gelijk is aan klasse2Geroerd, klasse2Ongeroerd of klasse2Ongedifferentieerd en de waarde van het attribuut geotechnische grondsoort gelijk is aan keien, keienMetGrind, keienMetZand, keienMetSilt, keienMetKlei, keitjes, keitjesMetGrind, keitjesMetZand, keitjesMetSilt, keitjesMetKlei, grind, grindMetKeien, grindMetKeitjes, zwakZandigGrind, sterkZandigGrind, siltigGrind, kleiigGrind, zand, zandMetKeien, zandMetKeitjes, zwakGrindigZand, sterkGrindigZand, siltigZand, siltigZandMetGrind, kleiigZand of kleiigZandMetGrind. De entiteit mag niet aanwezig zijn in alle andere gevallen.`

## Oplossingsrichting
moet zijn:
_De entiteit moet aanwezig zijn wanneer de waarde van het attribuut beschrijfkwaliteit van de entiteit Boorprofiel gelijk is aan klasse2**g**eroerd, klasse2**o**ngeroerd of klasse2**o**ngedifferentieerd en de waarde van het attribuut geotechnische grondsoort gelijk is aan keien, keienMetGrind, keienMetZand, keienMetSilt, keienMetKlei, keitjes, keitjesMetGrind, keitjesMetZand, keitjesMetSilt, keitjesMetKlei, grind, grindMetKeien, grindMetKeitjes, zwakZandigGrind, sterkZandigGrind, siltigGrind, kleiigGrind, zand, zandMetKeien, zandMetKeitjes, zwakGrindigZand, sterkGrindigZand, siltigZand, siltigZandMetGrind, kleiigZand of kleiigZandMetGrind. De entiteit mag niet aanwezig zijn in alle andere gevallen._

**Comment by BregjeBrugman** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
