### ISSUE TITLE
Combinatie van bepaalde boortechnieken levert probleem op vanwege attribuut "spoeling gebruikt"

### ISSUE THREAD

**Issue by ArthurDeMoel** [BROprogramma/BHR-GT#171]
## Type issue
Opmerking uit implementatie

## Waar
BRO catalogus  15-04-2019, pag. 34, par. 7.0.14
BRO catalogus  31-10-2019, pag. 33, par. 3.8.14

## Beschrijving probleem
Bij een boring kan sprake zijn van meerdere toegepaste boortechnieken, bijvoorbeeld mechanischDraaienOnverbuisd(Avegaar) en mechanischPulsen. Bij de eerstgenoemde techniek moet je in de BRO vermelden of er spoeling is gebruikt, bij de tweede moet dit veld ontbreken. Oftewel, aanleveren van de 2 genoemde boortechnieken samen kan niet en gaat fout bij de validatie, omdat je alleen voor de boring in zijn geheel kan aangeven of er spoeling is gebruikt en niet per boortechniek. 

## Oplossingsrichting
Het attribuut 'Spoeling gebruikt' opnemen in het onderdeel "Geboord interval" waar ook de boortechniek vermeld wordt.

## Workaround
Onjuiste informatie aan de BRO aanleveren door in bovengenoemd geval 1 boortechniek aan te leveren i.p.v. 2, hetgeen niet wenselijk is.

**Comment by fterpstra** [comment]
Spoeling gebruikt staat op het juiste niveau, het gaat er om dat wanneer er in 1 van de geboorde intervallen spoeling is gebruikt dit relevant is voor het gehele traject. De regel is ook goed geïmplementeerd in de LV (is gecheckt bij Sjaak). Wanneer het nog steeds onduidelijk is kan de toelichting worden uitgebreid (in versie 1.99).

**Comment by ArthurDeMoel** [comment]
Beste Frank,

Bedankt voor je reactie, maar zo makkelijk kom je niet van me af ☺. Ik ben het er namelijk (grotendeels) niet mee eens en ik heb sterk de indruk dat jullie mijn beschrijving van het probleem op GitHub niet goed hebben gelezen.  Het probleem licht ik in deze e-mail nog eens graag toe, mede aan de hand van een concreet voorbeeld. De regel/validatie aangaande het attribuut  ‘spoeling gebruikt’ is weliswaar geïmplementeerd zoals het in de BRO-catalogus staat, maar in deze regel zit een denkfout en dat levert in bepaalde gevallen een fout op bij het valideren. Tevens kwam ik er achter dat dit ook voor het attribuut ‘ tijdelijke verbuizing aangebracht’ geldt.

Wanneer tijdens een booronderzoek geroerde monsters worden genomen, dan worden hierbij vaak 2 boormethodes gebruikt, namelijk avegaar (in de BRO ‘mechanischDraaienOnverbuisd’) en pulsen (mechanischPulsen). Zo ook in het meegeleverde booronderzoek in de bijlage:

1.       Geboord interval van 0 to 2.7m, gebruikte boortechniek ‘mechanischDraaienOnverbuisd’.

2.       Geboord interval van 2.7m to 6.0m, gebruikte boortechniek ‘mechanischPulsen’.

De eerstgenoemde boortechniek ‘mechanischDraaienOnverbuisd’ vereist dat de attributen ‘spoeling gebruikt’ en ‘tijdelijke verbuizing aangebracht’ aanwezig moeten zijn.
De tweede boortechniek ‘mechanischPulsen’ vereist dat deze attributen moeten ontbreken.

Deze regels botsen !! En dat blijkt ook uit de foutmelding die ik bij het valideren krijg:
{
  "status":"NIET_VALIDE",
  "errors":
  [
    "Boring.spoeling gebruikt (Boring.flushingMediumUsed) mag niet aanwezig zijn: Geboord interval.boortechniek (BoredInterval.boringTechnique) = mechanischPulsen bepaalt dat het moet ontbreken.",
    "Boring.tijdelijke verbuizing (Boring.temporaryCasingUsed) mag niet aanwezig zijn: Geboord interval.boortechniek (BoredInterval.boringTechnique) = mechanischPulsen bepaalt dat het moet ontbreken.",
    "Er zijn 1 of meer fouten geconstateerd in het brondocument."
  ]
}

N.B. Als ik de attributen weg laat, krijg ik uiteraard een foutmelding dat de attributen aanwezig moeten zijn vanwege de boortechniek ‘mechanischDraaienOnverbuisd’.

Oftewel, het aanleveren van deze 2 boortechnieken in 1 booronderzoek is onmogelijk, terwijl deze 2 boortechnieken in de praktijk vaak samen voorkomen. Ik mag aannemen dat het nu duidelijk is.

Als jullie de betreffende attributen op het huidige niveau willen laten staan is dat prima, maar dan zal er wel een wijziging in de validatie moeten komen. Beste oplossing lijkt mij om hierbij te checken of er een boortechniek gebruikt is die de aanwezigheid van deze attributen vereist. Indien ja, dan moeten de attributen altijd in de XML opgenomen worden, ongeacht de aanwezigheid van andere boortechnieken. Indien dit niet het geval is, dan moeten ze ontbreken.


Met vriendelijke groet,

Arthur de Moel
Hoofd ICT, vestiging Rotterdam

MOS GRONDMECHANICA B.V.




Tel. algemeen:
Tel. direct:

+31 (0)88 - 51 30 200
+31 (0)88 - 51 30 215









Website:
E-mail:

http://www.mosgeo.com<http://www.mosgeo.com/>
a.demoel@mosgeo.com<mailto:a.demoel@mosgeo.com>







Bezoekadres:

Albert Plesmanweg 47, 3088 GB, Rotterdam



Dit e-mailbericht is uitsluitend bestemd voor de geadresseerde(n) en kan vertrouwelijke informatie bevatten. Als het bericht niet voor u bestemd is, wordt u vriendelijk verzocht dit aan de afzender te melden en het bericht te verwijderen. Het is niet toegestaan om de inhoud van het bericht, geheel of gedeeltelijk, zonder toestemming te gebruiken, te kopiëren of te verspreiden.
Mos Grondmechanica B.V. accepteert geen aansprakelijkheid voor het niet tijdig, onjuist of onvolledig ontvangen van dit bericht.

Van: Frank Terpstra [mailto:notifications@github.com]
Verzonden: dinsdag 18 februari 2020 16:16
Aan: BROprogramma/BHR-GT <BHR-GT@noreply.github.com>
CC: Arthur de Moel <A.deMoel@mosgeo.com>; Author <author@noreply.github.com>
Onderwerp: Re: [BROprogramma/BHR-GT] Combinatie van bepaalde boortechnieken levert probleem op vanwege attribuut "spoeling gebruikt" (#171)


Spoeling gebruikt staat op het juiste niveau, het gaat er om dat wanneer er in 1 van de geboorde intervallen spoeling is gebruikt dit relevant is voor het gehele traject. De regel is ook goed geïmplementeerd in de LV (is gecheckt bij Sjaak). Wanneer het nog steeds onduidelijk is kan de toelichting worden uitgebreid (in versie 1.99).

**Comment by WijnandvanRiel** [comment]
Het gaat (zoals Arthur al aangaf) om twee attributen. Hieronder in **vet** de volledig uitgeschreven regels

Tijdelijke verbuizing aangebracht (Attribuut van Boring)

- Regels: Het gegeven is aanwezig wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval (**lees: de boortechniek in ten minste 1 van de geboorde intervallen**) gelijk is aan handDraaien, mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd of mechanischSpuitenDraaien. 
In andere gevallen ontbreekt het gegeven.
**Voluit: Het attribuut mag niet aanwezig zijn wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval in geen van de geboorde intervallen gelijk is aan handDraaien, mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd of mechanischSpuitenDraaien.**
2.	spoeling gebruikt (Attribuut van Boring)
Regels: 

- Het gegeven is aanwezig wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval **(lees: de boortechniek in ten minste 1 van de geboorde intervallen)** gelijk is aan mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd of mechanischSpuitenDraaien. 

- In andere gevallen ontbreekt het gegeven. 
**Voluit: Het attribuut mag niet aanwezig zijn wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval in geen van de geboorde intervallen gelijk is aan mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd of mechanischSpuitenDraaien.**

Regels IMBRO/A:
- Wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval gelijk is aan mechanischDraaienOnverbuisdDeelsDrukkenHameren is het gegeven ook aanwezig.

Voluit uitgeschreven voor IMBRO/A is dat:
****- Het attribuut moet aanwezig zijn wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval in ten minste 1 van de geboorde intervallen gelijk is aan mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd, mechanischSpuitenDraaien of mechanischDraaienOnverbuisdDeelsDrukkenHameren).**
**- Het attribuut mag niet aanwezig zijn wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval in geen van de geboorde intervallen gelijk is aan mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd, mechanischSpuitenDraaien of mechanischDraaienOnverbuisdDeelsDrukkenHameren  ontbreekt het gegeven.****

**Comment by ArthurDeMoel** [comment]
Hoi Wijnand,

Ja, dat zou het probleem op moeten lossen ! Bedankt.

N.B. Ik begrijp dat implementatie in de validatie nog even kan duren, maar dat is geen probleem.

Met vriendelijke groet,

Arthur de Moel
Hoofd ICT, vestiging Rotterdam

MOS GRONDMECHANICA B.V.




Tel. algemeen:
Tel. direct:

+31 (0)88 - 51 30 200
+31 (0)88 - 51 30 215









Website:
E-mail:

http://www.mosgeo.com<http://www.mosgeo.com/>
a.demoel@mosgeo.com<mailto:a.demoel@mosgeo.com>







Bezoekadres:

Albert Plesmanweg 47, 3088 GB, Rotterdam



Dit e-mailbericht is uitsluitend bestemd voor de geadresseerde(n) en kan vertrouwelijke informatie bevatten. Als het bericht niet voor u bestemd is, wordt u vriendelijk verzocht dit aan de afzender te melden en het bericht te verwijderen. Het is niet toegestaan om de inhoud van het bericht, geheel of gedeeltelijk, zonder toestemming te gebruiken, te kopiëren of te verspreiden.
Mos Grondmechanica B.V. accepteert geen aansprakelijkheid voor het niet tijdig, onjuist of onvolledig ontvangen van dit bericht.

Van: Wijnand [mailto:notifications@github.com]
Verzonden: vrijdag 21 februari 2020 10:24
Aan: BROprogramma/BHR-GT <BHR-GT@noreply.github.com>
CC: Arthur de Moel <A.deMoel@mosgeo.com>; Author <author@noreply.github.com>
Onderwerp: Re: [BROprogramma/BHR-GT] Combinatie van bepaalde boortechnieken levert probleem op vanwege attribuut "spoeling gebruikt" (#171)


Het gaat (zoals Arthur al aangaf) om twee attributen. Hieronder in vet de volledig uitgeschreven regels

Tijdelijke verbuizing aangebracht (Attribuut van Boring)

  *   Regels: Het gegeven is aanwezig wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval (lees: de boortechniek in ten minste 1 van de geboorde intervallen) gelijk is aan handDraaien, mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd of mechanischSpuitenDraaien.
In andere gevallen ontbreekt het gegeven.
Voluit: Het attribuut mag niet aanwezig zijn wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval in geen van de geboorde intervallen gelijk is aan handDraaien, mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd of mechanischSpuitenDraaien.

  1.  spoeling gebruikt (Attribuut van Boring)
Regels:

·         Het gegeven is aanwezig wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval (lees: de boortechniek in ten minste 1 van de geboorde intervallen) gelijk is aan mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd of mechanischSpuitenDraaien.

·         In andere gevallen ontbreekt het gegeven.
Voluit: Het attribuut mag niet aanwezig zijn wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval in geen van de geboorde intervallen gelijk is aan mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd of mechanischSpuitenDraaien.

Regels IMBRO/A:

  *   Wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval gelijk is aan mechanischDraaienOnverbuisdDeelsDrukkenHameren is het gegeven ook aanwezig.

Voluit uitgeschreven voor IMBRO/A is dat:
- Het attribuut moet aanwezig zijn wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval in ten minste 1 van de geboorde intervallen gelijk is aan mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd, mechanischSpuitenDraaien of mechanischDraaienOnverbuisdDeelsDrukkenHameren).
- Het attribuut mag niet aanwezig zijn wanneer de waarde van het attribuut boortechniek van de entiteit Geboord interval in geen van de geboorde intervallen gelijk is aan mechanischDraaienOnverbuisd, mechanischGrijpen, mechanischSpuitenOnverbuisd, mechanischSpuitenDraaien of mechanischDraaienOnverbuisdDeelsDrukkenHameren ontbreekt het gegeven.

**Comment by fterpstra** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
