### ISSUE TITLE
Probleem aanleveren korrelverdeling t.g.v. de door de BRO opgelegde afronding op 1 decimaal

### ISSUE THREAD

**Issue by ArthurDeMoel** [BROprogramma/BHR-GT#172]
**Type issue**
Opmerking uit implementatie

**Waar**
BRO catalogus van 31-10-2019, paragraaf. 3.63 t/m 3.67

**Beschrijving probleem**
De aan te leveren waarden van de fracties van de korrelverdeling moeten afgerond worden op 1 decimaal conform de BRO catalogus . Bij het valideren levert dit meestal een fout op en wel hierom; als je alle aparte fracties bij elkaar optelt, komt hier vaak een andere waarde uit dan de totaalwaarde (i.e. fractionLarger63um) die je ook moet aanleveren. Zoals in het voorbeeld hieronder is de (echte) totale waarde van de fracties groter dan 63 um gelijk aan 95.5%, maar alle losse fracties bij elkaar opgeteld levert een waarde op van 95.6%:

_Stukje uit XML-bestand:_
<ns2:fractionLarger63um uom="%">95.5</ns2:fractionLarger63um>
<ns2:standardDistributionFractionLarger63um>
<ns2:fraction63to90um uom="%">2.7</ns2:fraction63to90um>
<ns2:fraction90to125um uom="%">9.8</ns2:fraction90to125um>
<ns2:fraction125to180um uom="%">35.6</ns2:fraction125to180um>
<ns2:fraction180to250um uom="%">26.4</ns2:fraction180to250um>
<ns2:fraction250to355um uom="%">15.7</ns2:fraction250to355um>
<ns2:fraction355to500um uom="%">4.0</ns2:fraction355to500um>
<ns2:fraction500to710um uom="%">1.0</ns2:fraction500to710um>
<ns2:fraction710to1000um uom="%">0.2</ns2:fraction710to1000um>
<ns2:fraction1000to1400um uom="%">0.1</ns2:fraction1000to1400um>
<ns2:fraction1400umto2mm uom="%">0.1</ns2:fraction1400umto2mm>
<ns2:fraction2to4mm uom="%">0.0</ns2:fraction2to4mm>
<ns2:fraction4to8mm uom="%">0.0</ns2:fraction4to8mm>
<ns2:fraction8to16mm uom="%">0.0</ns2:fraction8to16mm>
<ns2:fraction16to31_5mm uom="%">0.0</ns2:fraction16to31_5mm>
<ns2:fraction31_5to63mm uom="%">0.0</ns2:fraction31_5to63mm>
<ns2:fractionLarger63mm uom="%">0.0</ns2:fractionLarger63mm

En pats boem, bij de validatie krijg je dan de melding dat deze twee waarden niet hetzelfde zijn (validatieservice berekent zelf de som van alle aangeleverde losse fracties en vergelijkt die met de aangeleverde totaalwaarde. Meerdere decimalen aanleveren is de oplossing niet, heb ik namelijk al geprobeerd, BRO rond dit zelf af). Oorzaak dat deze waarden vaak van elkaar af zullen wijken is dus de afronding op 1 decimaal. In het minst gunstige geval levert dat voor de 16 verschillende fracties (er van uitgaande dat ze allemaal aanwezig zijn) een afrondingsfout van 16x 0.05% = 0.8% op (In de praktijk zal dit meestal tussen de 0 en 0.2% liggen, aangezien de afrondingen zelden allemaal dezelfde kant op zullen zijn en individueel meestal kleiner dan ±0.05% zullen zijn). Ook komt het er op neer dat de som van alle losse fracties groter dan 100% zou kunnen zijn. Oftewel, niet goed over nagedacht. Jammer. 
 
**Mogelijke oplossing**
Ik heb 3 verschillende korrelverdelingen geprobeerd te valideren, alle 3 niet valide om bovenstaande reden. Het gaat vaker fout dan goed. Mijns inziens is de beste oplossing om met 2 decimalen te gaan werken. Voorwaarde is wel dat de BRO bij het valideren ook met die 2 decimalen rekent. Dat zou betekenen dat bij het berekenen van de som van de losse fracties er maximaal 16x 0.005% = 0.08% afwijking zou kunnen zijn t.o.v. de totaalwaarde die ook aangeleverd moet worden. Bij het valideren moet dat verschil ook toegestaan worden, evenals het feit dat de som nog steeds iets groter zou kunnen zijn dan 100%.
 
N.B. het lijkt mij persoonlijk een slechte zaak om als oplossing bepaalde waarden de verkeerde kant af te gaan ronden om het toch kloppend te krijgen. Ik heb het wel bij eentje geprobeerd en die kwam toen inderdaad door de validatie heen (zie bestand met gemanipuleerd in de titel).

[XML voorbeelden.zip](https://github.com/BROprogramma/BHR-GT/files/3915355/XML.voorbeelden.zip)

**Comment by RuudMutsaers** [comment]
Het vermelde issue betreft het feit dat er inhoudelijke afspraken gemaakt zijn over:
1. De notatiewijze en nauwkeurigheid van noteren.
2. De afspraak over de totaalwaarde van de korrelverdeling.

Daarnaast wordt er een link gelegd met de technische aspecten van de LV te weten
3. Hoe wordt er bij de LV omgegaan bij het ontvangen van waardes met meer decimalen dan is afgesproken.

Antwoorden:
1. Tijdens de standaardisatiebijeenkomsten met de laboratoria is afgesproken dat de nauwkeurigheid van de percentages met 1 decimaal nauwkeurig zou worden uitgewisseld aangezien dit een realistische en zinvolle nauwkeurigheid is van de betreffende informatie. Dit is dus in de vorm van een waarde-domein als afspraak opgenomen in de catalogus.

2. Tijdens de standaardisatiebijeenkomsten met de laboratoria is gesproken over het feit dat er binnen de bepaling verschil kan zijn tussen het gewicht vooraf en achteraf. Dit kan verschillende oorzaken hebben. afronding is er 1 van. Vanuit de labs is aangegeven dat zij altijd het geheel weer terug rekenen naar een 100 % verdeling. Dit is de grondslag waarop de 100% regel is gebaseerd. In deze regel zit dus tevens omsloten dat het lab daarvoor verantwoordelijk is. 

3. Bij de landelijke voorziening is afgesproken hoe we omgaan met het aanbieden van waarden met meer decimalen zoals afgesproken en vastgelegd in de catalogus. Feit is dat deze decimalen bij de LV worden afgekapt. Het betekend dat een waarde waarvan is afgesproken dat die met 1 decimaal wordt aangeleverd en wordt aangeboden als 1,99 in de BRO wordt opgenomen als 1,9. De fout of onnauwkeurigheid die hierdoor kan ontstaan ligt bij de verantwoordelijkheid van de leverancier. Als het niet wenselijk is dat daar zo mee omgegaan wordt dient hij zelf de juiste waarde in 1 decimaal nauwkeurig aan te bieden. 

Als blijkt dat de inhoudelijke aspecten die afgesproken zijn tijdens het standaardisatietraject niet juist zijn moeten we daar nog eens naar kijken. Echter zijn we van mening dat die afspraken goed gemaakt zijn. Het lijkt er dus op dat de afspraak die gemaakt is m.b.t. aspect 2 nog niet goed geimplementeerd is waardoor dit probleem ontstaat bij het aanleveren van de gegevens.

**Comment by RuudMutsaers** [comment]
De afspraak is gemaakt dat de producent de korrelgrootte verdeling op 100 % aanleverd. In  het geval dat de afronding dat niet doet moet er dus een correctie plaatsvinden.
