### ISSUE TITLE
Uitvoerder Beschrijving

### ISSUE THREAD

**Issue by JPietersen** [BROprogramma/BHR-GT#174]
## Type issue
Publieke consultatie

## Waar
3.19.3 Uitvoerder Beschrijving als onderdeel van Boormonsterbeschrijving

## Samenvatting
Indien een opdrachtgever bedrijf 'A' inhuurt voor het maken van een boring en bijhorende boormonsterbeschrijving, en bedrijf 'B' inhuurt voor labwerk en lab-beschrijving(en), zou Uitvoerder beschrijving niet onderdeel moeten zijn van Boormonsterbeschrijving, maar onderdeel van de onderliggende Boorprofielen.

## Beschrijving
Wanneer taken voor boren en labwerk door een opdrachtgever verdeeld worden, zijn beide bedrijven verantwoordelijk voor hun eigen werk. Bij uitbesteed werk is dit niet aan de orde.
Nu is er geen mogelijkheid deze onderverdeling te maken.

## Oplossingsrichting
Als uitvoerder beschrijving onderdeel is van Boorprofiel, kan elk profiel verantwoordelijkheid zijn van een ander bedrijf.

**Comment by fterpstra** [comment]
Nogmaals dank voor uw reactie. De publieke consultatie is verwerkt,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
