### ISSUE TITLE
TX Filterstrookcorrectie 45tot50 %

### ISSUE THREAD

**Issue by JPietersen** [BROprogramma/BHR-GT#175]
## Type issue
Publieke consultatie

## Waar
Codelijst 1.4 Bedekkingsgraad
(filterstrookjescorrectie triaxiaalproef)

## Samenvatting
De mogelijkheid 45tot50 % ontbreekt in de codelijst

## Beschrijving 
Bij de mogelijkheden voor bedekkingsgraad van filterstroken ontbreekt de mogelijkheid 45tot50. In de norm (ISO 17892-9) staat: Vertically oriented filter paper strips (...) shall not cover more than 50% of the specimen's radial surface. In de praktijk wordt ook een bedekking tussen 45 en 50 % gebruikt.

## Oplossingsrichting
Uitbreiden codelijst met de mogelijkheid 45tot50

**Comment by fterpstra** [comment]
Nogmaals dank voor uw reactie. De publieke consultatie is verwerkt,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
