### ISSUE TITLE
TX Consolidatiefase / Bepalingsmethode

### ISSUE THREAD

**Issue by JPietersen** [BROprogramma/BHR-GT#176]
## Type issue
Publieke consultatie

## Waar
3.44 Consolidatiefase (TX): regels

## Samenvatting
Bij de regels van Consolidatiefase staan eisen die niet aansluiten op een trixaiaalproef met consolidatiefase.

## Beschrijving
Consolidatiefase moet aanwezig zijn wanneer bepalingsmethode 'bepaling schuifspanningsverloop bij belasting' gelijk is aan 'belastenGeconsolideerdGedraineerd' of 'belasten**Geconsolideerd**Ongedraineerd'. Nu verwijst de tweede mogelijheid naar 'belasten**Ongeconsolideerd**Ongedraineerd'

## Oplossingsrichting
In de Regels van 3.44 Consolidatiefase 'belasten**Ongeconsolideerd**Ongedraineerd' vervangen door 'belasten**Geconsolideerd**Ongedraineerd'

**Comment by fterpstra** [comment]
Nogmaals dank voor uw reactie. De publieke consultatie is verwerkt,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
