### ISSUE TITLE
Oude termen in codelijst TypeAnalyse

### ISSUE THREAD

**Issue by JPietersen** [BROprogramma/BHR-GT#177]
## Type issue
Publieke consultatie

## Waar
Codelijst 1.91: TypeAnalyse toelichting van 'korrelverdeling'

## Samenvatting
'Bepaling verticale vervorming' uit werkversie 0.99 is in de versie van 31/10/2019 vervangen door 'bepaling zettingseigenschappen'

## Beschrijving
In de toelichting wordt naar een bepaling 'verticale vervorming' verwezen die inmiddels 'zettingseigenschappen' genoemd is.

## Oplossingsrichting
Vervangen verwijzing naar 'zettinsgeigenschappen'

**Comment by fterpstra** [comment]
Nogmaals dank voor uw reactie. De publieke consultatie is verwerkt,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
