### ISSUE TITLE
Nieuwe methode locatie en positiebepaling (PPP)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#178]
## Type issue
Standaardisatie geologisch booronderzoek

## Waar
MethodeLocatiebepaling (waardelijst 63)
MethodeVerticalePositiebepaling (waardelijst 65)

## Samenvatting
Nieuwe methode Precise Point Positioning (PPP) voor het bepalen van de locatie en de positie.

## Beschrijving
Tijdens de standaardisatie van het geologisch booronderzoek is de nieuwe methode PPP aangedragen. Een methode die voornamelijk op zee steeds meer wordt gebruikt. 

## Oplossingsrichting
Toevoegen nieuwe waarde aan de waardelijsten MethodeLocatiebepaling en MethodeVerticalePositiebepaling.

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
