### ISSUE TITLE
boormonsterbeschrijving

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#18]
Pagina 28 van 182 alinea 2:
zinsdeel: "....van het deelonderzoek boormonsterbeschrijving."

Wordt hierbij specifiek de "veldbeschrijving" bedoeld?
- Zo ja, waarom dan ook niet noemen zoals het bedoeld word?
- Zo niet, dan beter duiden dat meer optie mogelijk zijn door bijvoorbeeld het benoemen van voorbeelden.

**Comment by fterpstra** [comment]
zie antwoord bij #17
