### ISSUE TITLE
gevlekt (Grond) niet verplicht

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#180]
## Type issue
implementatie

## Waar
gevlekt (attribuut van Grond, 22.7)

## Samenvatting
gevlekt niet relevant

## Beschrijving
De aanduiding of vlekken voorkomen was verplicht in de BRO. Voort GT niet relevant, wordt niet genoemd in norm. 

## Oplossingsrichting
De regel bij gevlekt vervalt.

**Comment by fterpstra** [comment]
Dit issue is verwerkt maar anders dan hierboven omschreven: het is alleen verplicht bij ongeroerd
