### ISSUE TITLE
Grondwaterstand

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#181]
## Type issue
Publieke consultatie

## van
Inpijn-Blokpoel

## plek
pagina 34 paragraaf3.8.16 

## oplossingsrichting
Er mist een indicatie van de GLG en GHG   (gemiddelde hoogste en gemiddelde laagste grondwaterstand). Deze geven een   goede indicatie over de grondwaterfluctieaties in het boorgat.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
