### ISSUE TITLE
Ondergrond verontreiniging

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#182]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
pagina 35 paragraaf 3.8.19

## Beschrijving
Zou hier niet ook   de optie 'onbekend' aan toegevoegd moeten worden

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
