### ISSUE TITLE
Containerlengte 

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#183]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
pagina 44 paragraaf 3.13.3

## Beschrijving
Waardebereik 0,05   tot 40 meter. Containers van   40 meter? Klopt de eenheid wel? Moet dit niet 0,05 tot ca 100 cm zijn? Een   Ackermansteekbus is 44 cm. Waarschijnlijk de meestgebruikte container.   Aangezien bij boren maximale lengte per steekmonster 1 meter is, lijkt 40   meter niet correct.

**Comment by JPietersen** [comment]
Vanuit boringen op water zijn deze lange containerlengten wel degelijk realistisch.
40 meter lang is hierin wel een zeldzaamheid, maar bijvoorbeeld Vibrocores van 5,50 meter komen regelmatig voor. 
Bij gesteente kernen wordt meestal ca 27 meter in één stuk gekernd.
Ik zou daarom adviseren dit waardebereik niet aan te passen.

**Comment by fterpstra** [comment]
ogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
