### ISSUE TITLE
Beschrijfkwaliteit (waardelijst)

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#184]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
pagina 58 paragraaf 3.20.1 

## Gerelateerd issue
#214 Beschrijfkwaliteit (= duplicaat)

## Beschrijving
De waardes die bij deze attribuut horen   zijn niet conform de norm (B2/B3 en QM1 t/m QM5) en gaan voor verwarring   zorgen.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
