### ISSUE TITLE
Bepaling ondergrens

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#185]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
 pagina 65 paragraaf 3.21.4 

## Beschrijving
Wellicht specificeren dat de bepaling   ondergrens gelijk is aan de bepaling bovengrens van de onderliggende laag.   Dit omdat de norm 14688-1 stelt dat enkel de bovengrens moet worden   beschreven van de laag.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
