### ISSUE TITLE
naamgeving scheefstaand

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#186]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
Pagina 66 paragraaf 3.21.8 

## Beschrijving
Er wordt normaal gesproken over   'scheefstand' en niet 'scheefstaand'

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
