### ISSUE TITLE
Grondsoorten   NEN5104 

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#187]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
pagina 69 paragraaf 3.22.2 

## Beschrijving
 In de toelichting staat nadere spcificatie   van Veen genoemd. Hierins staat o.a. dy. Dit moet humus zijn volgens   NEN-EN-ISO 14688-1 figuur NA.1

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
