### ISSUE TITLE
Ringdiameter 

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#188]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
pagina 107 paragraaf 3.31.4 

## Beschrijving
Ringhoogte varieert tussen de 20 en 60 mm. Verder moet hier ook   bij vermeld worden welke afwijking er mag zijn van de gekozen diameter, +/- 1   mm?

**Comment by JPietersen** [comment]
Indien er gewerkt zou gaan worden met toegestane afwijkingen van de gekozen diameter, is het wellicht netter om dit attribuut te vervangen door een meetwaarde.

**Comment by fterpstra** [comment]
ogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
