### ISSUE TITLE
Spanning bij   bepaalde zetting 

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#189]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
pagina 120 paragraaf 3.37 

## Beschrijving
In de toelichting staat: "Bij een   relaxatiestap wordt alleen de verticale korrelspanning bepaald." Dit is   niet juist. De waterspanning wordt zowel bij belasten, ontlasten als   relaxatie gemeten. Je kan anders nooit de effectieve spanning in het monster   . Uit deze stap wordt de c-parameter bepaald.bepalen.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
