### ISSUE TITLE
BOX Registratieobject

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#19]
Pagina 30 van 182 schema:
(HvM)
Als dat aan de orde is dan moet er een duidelijke koppeling zijn met de betreffende grondwatermonitoringput. Bij het plaatsen van een grondwatermonitoringput wordt vaak voorzien in een boorbeschrijving.

**Comment by fterpstra** [comment]
antwoord Robert-Jan van Leeuwen:
"Die koppeling gaat impliciet ontstaan omdat er op dezelfde plaats een booronderzoek en een grondwatermonitoringput zullen zijn."
