### ISSUE TITLE
Verschilwaterspanning

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#190]
## Type issue
Publieke consultatie

## Van 
Inpijn-Blokpoel

## Waar
Pagina 121 paragraaf 3.37.3 

## Beschrijving
Attribuut moet ook aanwezig zijn tijdens de   relaxatiestap.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
