### ISSUE TITLE
Horizontale   korrelspanning

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#191]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
pagina 122 paragraaf 3.37.5 

## Beschrijving
Bij regels, specificeren wanneer het   attribuut aanwezig mag zijn. Want is geen vereiste.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
