### ISSUE TITLE
Bepalingsprocedure

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#192]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
PAgina 123 paragraaf 3.38.1

## Beschrijving
in de toelichting staat NEN-en-ISO   146888-2, dit moet zijn NEN-EN-ISO 14688-2

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
