### ISSUE TITLE
Bepaling   schuifspanningsverloop bij belasting 

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#193]
## Type issue
Publieke consultatie

## Van 
Inpijn-Blokpoel

## Waar
Pagina 126 paragraaf 3.39

## Beschrijving
In de toelichting staat:"   Normaliter/idealiter omvat het proefstuk de volledige doorsnede van het   boormonster". Dit kan beter veranderd worden in: "Idealiter heeft   het proefstuk een zo groot mogelijke diameter, doch minimale diameter bedraagt   50 mm."

**Comment by JPietersen** [comment]
In lijn met de NEN 17892-8/9 en de BRO (3.39.6) is de minimale diameter 35mm.
Waarschijnlijk is de huidige toelichting echter afdoende.

**Comment by fterpstra** [comment]
ogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
