### ISSUE TITLE
Proefstuk getrimd

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#194]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
Pagina 129 paragraaf 3.39.5

## Beschrijving
In de toelichting staat: de opmerking 'Dit   komt weinig' voor mag er uit worden gehaald. Proefstukken worden meestal van   66 mm naar 50 mm teruggetrimd.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
