### ISSUE TITLE
Membraan vooraf   verzadigd

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#195]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
PAgina 130 paragraaf 3.39.10 

## Beschrijving
In de toelichting staat "Meestal wordt   het membraan nadat het om het proefstuk is getrokken met een kwastje of spuit   aan de buitenkant nat gemaakt". Deze zin kan verwijderd worden aangezien   dit lang niet voor alle labs geldt, irrelevant is en erg onwetenschappelijk   klinkt.

**Comment by JPietersen** [comment]
Dit punt is tijdens de werkgroepsessies besproken. Omdat er op dit punt bewust van de norm wordt afgeweken, is deze toelichting relevant.
Vooraf verzadigen van het membraan stuit op praktische bezwaren, zoals scheurende en lekkende membranen.

**Comment by fterpstra** [comment]
ogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
