### ISSUE TITLE
Schuifspanningsverloop   bij belasting

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#199]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
pagina 150 paragraaf 3.48 

## Beschrijving
In de toelichting specificeren dat het om   de triaxiaalproef gaat

## Oplossingsrichting

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
