### ISSUE TITLE
object-ID bronhouder: Tekst200

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#20]
Pagina 30 van 182 schema:
(HvM)
Er is nog steeds behoefte aan een 2e regel object-ID bronhouder: Tekst200.
Dit gezien het terug zoeken bij vragen (meldplicht) over een boring van het betreffende project (via WBS-element RWS) en het nummer van de betreffende boring (2e benodigde regel).
(PS: Overigens geldt bovenstaande ook voor onderandere sonderingen en waterput die reeds in tranche 1 zijn opgenomen!)

**Comment by fterpstra** [comment]
We blijven hier dezelfde lijn als bij sonderingen en waterput volgen.
