### ISSUE TITLE
Schuifspannings bij   bepaalde belasting

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#200]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
PAgina 151 paragraaf 3.49 

## Beschrijving
In de toelichting   specificeren dat het om de triaxiaalproef gaat

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
