### ISSUE TITLE
Bepalingsmethode 

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#201]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
Pagina 153 paragraaf 3.50.2 

## Beschrijving
Het proefstuk zit niet alleen vast tussen 2   poreuze stenen maar is ook zijdelings ondersteund (3.50.7). Misschien goed om   dit ook in de toelichting te vermelden.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
