### ISSUE TITLE
Schuifrek

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#205]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
Pagina 165 paragraaf 3.58.3 

## Beschrijving
Typefout in toelichting: (voestuk vast   =  nee):  moet zijn voetstuk vast= nee

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
