### ISSUE TITLE
definitie gebruikt medium (Bepaling consistentiegrenzen)

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#206]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
Pagina 168 paragraaf 3.59.3 

## Beschrijving
Definitie omschrijft dat er ook gas   gebruikt kan worden. Dit is niet juist, het betreft alleen het soort water.

**Comment by JPietersen** [comment]
Dit is een punt dat eigenlijk overal opduikt waar verwezen wordt naar de codelijst gebruiktMedium. Denk ook aan de optie 'bepaling waterdoorlatendheid' met als 'gebruikt medium' bijv 'hexaan'.
Misschien kan bij elk voorkomen van 'gebruikt medium' binnen de Regels beperkt worden uit welke waarden gekozen mag worden.

**Comment by fterpstra** [comment]
ogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
