### ISSUE TITLE
Aantal vallen

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#207]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
Pagina 172 paragraaf 3.61.3 

## Beschrijving
Waarde bereik staat op 0..30  maar in de norm staat 15 tot 40. Kunnen we   daar 0 tot 50 van maken?

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
