### ISSUE TITLE
BOX Boorprofiel

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#21]
Pagina 31 van 182 schema:

Bij een geotechnisch boring bepaal je normaal niet GHG/GLG (dat doe je obv een statistische analyse). Hooguit registreer je de waterstand in het boorgat.

**Comment by fterpstra** [comment]
antwoord Robert-Jan van Leeuwen:
"Normaal niet: dat zou kunnen, maar de experts hebben vastgesteld dat vastleggen wenselijk is. Het gaat om een waarneming en niet om een statistsiche afleiding (zie de definitie verderop in de catalogus))"
