### ISSUE TITLE
Stikstof als gebruikt medium (Bepaling volumieke massa vaste delen)

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#211]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
Pagina 222 paragraaf 3.76.3 

## Beschrijving
Voor het gas wordt alleen helium gebruikt.   Wij gebruiken stikstof (N2). Er was afgesproken dat we deze waarde ook moeten   kunnen meegeven. (zie regels en de toelichting)

**Comment by JPietersen** [comment]
Stikstof staat niet expliciet vermeld in de norm, enkel dat naast helium andere geschikte gassen gebruikt mogen worden. In lijn hiermee zou wellicht een optie 'gebruiktMedium: gasOverig' meerdere opties dekken. Tenzij stikstof specifieke voor/nadelen heeft.

**Comment by fterpstra** [comment]
ogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
