### ISSUE TITLE
Volumieke massa   vaste delen

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#212]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
Pagina 223 paragraaf 3.76.7

## Beschrijving
Eenheid staan in g/cm3; echter is   afgesproken dat de eenheid Mg/m3 is.    (verandert overigens niets aan de getallen)

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
