### ISSUE TITLE
Analyseprocedure

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#213]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
 Pagina 225 paragraaf 1.2 

## Beschrijving
NPR2020 zal waarschijnlijk NPR 2021 worden   aangezien er nog bijna niks is gedaan aan het tot stand komen van de NPR.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
