### ISSUE TITLE
Beschrijfkwaliteit (waardelijst): relatie beschrijfkwaliteit en monsterkwaliteit

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#214]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
Pagina 239 paragraaf 1.13 

## Gerelateerd issue
#144 relatie beschrijfkwaliteit en monsterkwaliteit
#184 Beschrijfkwaliteit (= duplicaat)

## Beschrijving
Waarom is er gekozen voor een afwijking   tenopzichte van de 14688-1? Zou het niet veel duidelijker zijn als hier alleen de waarde B1, B2, B3, en niet gespecificeerd als opties aanwezig zijn?   De mate van verstoring ligt vast in de monsterkwaliteit (1.66). Dit schept   verwarring.

## Oplossingsrichting

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
