### ISSUE TITLE
CO2 als gebruikt medium (triaxiaal)

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#215]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
Pagina 259 paragraaf 1.40

## Beschrijving
CO2 mist in het lijstje. CO2 wordt in de   triaxiaalproef gebruikt om zand makkelijker te laten verzadigen

**Comment by JPietersen** [comment]
CO2 wordt gebruikt als middel in de voorbehandeling van de verzadiging. De uiteindelijke verzadiging van het monster gebeurt met een medium dat wel degelijk in de lijst gebruiktMedium staat.
De mate van verzadiging zelf is vastgelegd dmv Skempton B-factor.
Als CO2 opgenomen zou worden in de lijst gebruikt medium, zou dit suggereren dat de triaxiaalproef is uitgevoerd met CO2 in de porien, ipv water, wat niet het geval is.

**Comment by fterpstra** [comment]
ogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie,  zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
