### ISSUE TITLE
Stikstof als gebruikt medium (Bepaling volumieke massa vaste delen)

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#216]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
 PAgina 259 Paragraaf 1.40

## Beschrijving
N2 (stikstof) mist in het lijstje. Stikstof   wordt naast Helium in de gaspycknometer gebruikt.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
