### ISSUE TITLE
Kalkgehalteklasse

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#217]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
Pagina 283 paragraaf 1.57 

## Beschrijving
 Indien er een 'Bepaling kalkgehalte' is   uitgevoerd kan het resultaat ook 'Zeer sterk kalkhoudend of carbonaat' zijn   (conform 14688-2). Deze waarde toevoegen.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
