### ISSUE TITLE
Organischestofgehalteklasse (waardelijst)

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#218]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar

Pagina 294 paragraaf 1.71 

## Beschrijving
Indien er een 'Bepaling   organischstofgehalte'is uitgevoerd kan het resultaat "matig   organisch" confrom 14688-2 niet verwerkt worden in de laagbeschrijving.   Is dit wenselijk of deze klasse toch wellicht nog toevoegen?

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
