### ISSUE TITLE
Stopcriterium

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#219]
## Type issue
Publieke consultatie

## Van 
Inpijn-Blokpoel

## Waar
Pagina 298 Paragraaf 1.86 

## Beschrijving
Typefout in de omschrijving   beperkingTechnisch: "de bepekingen van het gebruikte apparaat" moet   zijn "beperkingen   van…."

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
