### ISSUE TITLE
BOX Grond

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#22]
Pagina 31 van 182 schema:
Er zit veel in wat je vanuit geotechniek niet gebruikt (bodemkundige zaken), en ook geen feitelijke metingen zijn (bijv. ouderdom afzetting, etc.).

Attenbergse grenzen mogelijk toevoegen?

**Comment by fterpstra** [comment]
Antwoord Robert-Jan van Leeuwen:
"Atterbergse grenzen worden bepaald in het lab en vallen onder het onderdeel boormonsteronderzoek.
Alle gegevens die in het model staan hebben betrekking op geotechniek."
