### ISSUE TITLE
VerwijderdMateriaal 

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#220]
## Type issue
Publieke consultatie

## Van
Inpijn Blokpoel

## Waar
Pagina 309 paragraaf 1.99 

## Beschrijving
Suggestie: de waarde 'AntropogeenDiversen'   o.i.d. toevoegen. Er is bijvoorbeeld wel eens een stukje plastic of touw   aangetroffen.

## Oplossingsrichting

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
