### ISSUE TITLE
Wandwrijvingscorrectiemethode

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#221]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
PAgina 311 paragraaf 1.104 

## Beschrijving
Protocol laboratoriumproeven voor   grondonderzoek aan waterkeringen, 2019; het huidige protocol stamt uit 2016.   Er was sprake van een nieuw protocol in 2019, maar dat is nog niet   gepubliceerd. Het schijnt dat Deltares hier mee bezig is.

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
