### ISSUE TITLE
Plasticiteit

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/BHR-GT#222]
## Type issue
Publieke consultatie

## Van
Inpijn-Blokpoel

## Waar
missend gegeven

## Beschrijving
In de norm 14688-1 staat geschreven dat de   plasticiteit beschreven dient te worden zoals in tabel A.1 is gespecificeerd.   Deze bepaling komt nu niet terug in de BRO.

## Oplossingsrichting

**Comment by adbgnm** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie voor de verwerking en de catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
