### ISSUE TITLE
Consistentie fijne grond niet verplicht onder klasse 3

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#223]
## Type issue
implementatie

## Waar
consistentie fijne grond (attribuut van Grond)

## Samenvatting
Consistentie fijne grond niet verplicht voor klasse 3.

## Gerelateerd issus
#158 consistentie fijne grond niet voor QM5 (geroerd)
#225 schrijffout in regel bij consistentie fijne grond

## Beschrijving
Het beschrijven van de consistentie fijne grond is voor klasse 3 niet  verplicht.

## Oplossingsrichting
Aanpasing regel

**Comment by fterpstra** [comment]
In het correctieblad NEN14688 zijn een aantal wijzigingen doorgevoerd die betrekking hebben op het al dan niet verplicht vastleggen van bepaalde aspecten bij de beschrijving van grond. De gevolgen voor de verkennende klasse 3 beschrijvingen was niet helder. Nieuwe afspraak met de NEN commissie is dat er geen vrijheden onder klasse 3 beschrijvingen bestaan, zodat er in de praktijk ook een verschil tussen klasse 2 en klasse 3 beschrijvingen bestaat zoals de norm bedoeld. Dat betekent dat een aantal gegevens niet mag worden vastgelegd onder klasse 3 waaronder dit gegeven.
