### ISSUE TITLE
grindmediaanklasse (Onderzocht materiaal) alleen voor primaire fractie

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#224]
## Type issue
Implementatie

## Waar
grindmediaanklasse (attribuut van Onderzocht materiaal)

## Samenvatting
Grindmediaanklasse alleen voor de primaire fractie. 

## Gerelateerd issue
#134 grindmediaanklasse (Grond) alleen voor primaire fractie

## Beschrijving
De grindmediaanklasse wordt alleen vastgelegd voor de primaire fractie. 

## Oplossingsrichting
Aanpassing regel

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
