### ISSUE TITLE
schrijffout in regel bij consistentie fijne grond (klasse2geroerd en klasse2ongeroerd)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#225]
## Type issue
realisatie

## Waar
consistentie fijne grond (attribuut van Grond)

## Samenvatting
Schrijffout in regel bij verwijzing naar waarde.

## Gerelateerd issue
#158 consistentie fijne grond niet voor QM5 (geroerd)
#223 consistentie fijne grond niet verplicht voor klasse 3

## Beschrijving
CamelCase niet goed toegepast in regel bij klasse2Geroerd en klasse2Ongeroerd. Moet zijn klasse2geroerd en klasse2ongeroerd.

## Oplossingsrichting
verbetering regel.

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
