### ISSUE TITLE
schrijffout in regel bij kalkgehalteklasse (klasse2geroerd en klasse2ongeroerd)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#226]
## Type issue
realisatie

## Waar
kalkgehalteklasse (attribuut van Grond)

## Samenvatting
Schrijffout in regel bij verwijzing naar waarde.

## Gerelateerd issue
#131 kalkgehalteklasse bij monsterkwaliteit QM5
#132 kalkgehalteklasse bij organische en zeer grove gronden
#136 klasse-indeling bij kalkgehalteklasse
#227 kalkgehalteklasse onder klasse 3
#228 kalkgehalteklasse onder IMBRO/A
#243 kalkgehalteklasse onder klasse 3 (keuzevrijheid)

## Beschrijving
CamelCase niet goed toegepast in regel bij klasse2Geroerd en klasse2Ongeroerd. Moet zijn klasse2geroerd en klasse2ongeroerd.

## Oplossingsrichting
verbetering regel.

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
