### ISSUE TITLE
kalkgehalteklasse onder klasse 3

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#227]
## Type issue
implementatie

## Waar
kalkgehalteklasse (attribuut van Grond)

## Samenvatting
kalkgehalteklasse niet verplicht voor klasse 3.

## Gerelateerd issus
#131 kalkgehalteklasse niet voor QM5 (geroerd)
#132 kalkgehalteklasse niet bij organische en zeer grove gronden
#136 klasse-indeling kalkgehalteklasse
#226 schrijffout in regel bij kalkgehalteklasse
#228 kalkgehalteklasse onder IMBRO/A
#243 kalkgehalteklasse onder klasse 3 (keuzevrijheid)

## Beschrijving
Het beschrijven van de kalkgehalteklasse is voor klasse 3 niet  verplicht.

## Oplossingsrichting
Aanpassing regel

**Comment by fterpstra** [comment]
In het correctieblad NEN14688 zijn een aantal wijzigingen doorgevoerd die betrekking hebben op het al dan niet verplicht vastleggen van bepaalde aspecten bij de beschrijving van grond. De gevolgen voor de verkennende klasse 3 beschrijvingen was niet helder. Nieuwe afspraak met de NEN commissie is dat er geen vrijheden onder klasse 3 beschrijvingen bestaan, zodat er in de praktijk ook een verschil tussen klasse 2 en klasse 3 beschrijvingen bestaat zoals de norm bedoeld. Dat betekent dat een aantal gegevens niet mag worden vastgelegd onder klasse 3 waaronder dit gegeven.
