### ISSUE TITLE
kalkgehalteklasse onder IMBRO/A

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#228]
## Type issue
implementatie

## Waar
kalkgehalteklasse (attribuut van Grond)

## Samenvatting
Voor beschrijvingen onder NEN 5104 (IMBRO/A) geldt een andere klasse-indeling.

## Gerelateerd issus
#131 kalkgehalteklasse niet voor QM5 (geroerd)
#132 kalkgehalteklasse niet bij organische en zeer grove gronden
#136 klasse-indeling kalkgehalteklasse
#226 schrijffout in regel bij kalkgehalteklasse
#227 kalkgehalteklasse onder klasse 3
#243 kalkgehalteklasse onder klasse 3 (keuzevrijheid)

## Beschrijving
Als gevolg van de afspraken tussen NEN en BRO in het kader van consistentie zijn de waarden voor IMBRO aangepast. Deze nieuwe waarden gelden niet voor beschrijvingen gemaakt volgens NEN 5104 onder IMBRO/A. 

## Oplossingsrichting
Waarden voor IMBRO/A toevoegen en onderscheidend maken.

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
