### ISSUE TITLE
ruwheid (Korrelvorm) alleen bij zeer grove gronden

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#229]
## Type issue
implementatie

## Waar
ruwheid (attribuut van Korrelvorm)

## Samenvatting
De ruwheid van het korreloppervlak wordt alleen beschreven van keien en keitjes. 

## Beschrijving
De ruwheid van het korreloppervlak wordt alleen beschreven van de zeer groven gronden, en dat zijn keien en keitjes. 

## Oplossingsrichting
Aanpassing regel

**Comment by fterpstra** [comment]
De NEN14688 is aangepast, daarmee is dit issue komen te vervallen
