### ISSUE TITLE
Indicatie Antropogeen voor QM5 (geroerd)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#230]
## Type issue
implementatie

## Waar
antropogeen (attribuut van Laag)

## Samenvatting
Discrepantie tussen de BRO en de norm voor QM5. 

## Gerelateerd issue
#231 type ingreep bij antropogene lagen

## Beschrijving
In de BRO is het voor QM5 verplicht vast te leggen of een laag antropogeen is of niet en in de norm niet. 

## Oplossingsrichting
in lijn met elkaar brengen

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
