### ISSUE TITLE
type ingreep bij antropogene lagen

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#231]
## Type issue
implementatie

## Waar
type ingreep (attribuut van Laag)

## Samenvatting
type ingreep niet verplicht bij antropogene lagen

## Gerelateerd issue
#230 indicatie antropogeen voor QM5 (geroerd)

## Beschrijving
In het correctieblad van de 14688 is opgenomen dat type ingreep (bij antropogene lagen) niet verplicht is. 

## Oplossingsrichting
aanpassing regel

**Comment by fterpstra** [comment]
Dit issue is verwerkt maar anders dan hierboven omschreven: het is alleen verplicht bij ongeroerd
