### ISSUE TITLE
omschrijvingen waarden Monsterkwaliteit (waardelijst)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#232]
## Type issue
implementatie

## Waar
Monsterkwaliteit (waardelijst)

## Samenvatting
Omschrijvingen kwaliteitsniveaus monsters niet in lijn met 14688.

## Beschrijving
Omschrijvingen kwaliteitsniveaus monsters (Boormonsteranalyse) niet in lijn met 14688.

## Oplossingsrichting
verbetering omschrijvingen

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
