### ISSUE TITLE
schrijffout in regel bij monstervochtigheid (Boorprofiel)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#233]
## Type issue
realisatie

## Waar
monstervochtigheid (attribuut van Boorprofiel)

## Samenvatting
Schrijffout in regel bij verwijzing naar waarde.

## Gerelateerd issue
#131 kalkgehalteklasse bij monsterkwaliteit QM5

## Beschrijving
CamelCase niet goed toegepast in regel bij Gesteente. Moet zijn gesteente.

## Oplossingsrichting
verbetering regel.

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
