### ISSUE TITLE
organischestofgehalteklasse onder klasse 3

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#234]
## Type issue
implementatie

## Waar
organischestofgehalteklasse (attribuut van Grond)

## Samenvatting
organische stofgehalteklasse niet verplicht voor klasse 3

## Beschrijving
Aanpassing norm (correctieblad): organische stofgehalteklasse niet verplicht voor klasse 3.

## Oplossingsrichting
aanpassing regel

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
