### ISSUE TITLE
schrijffout in regel bij textuur organische grond (klasse2geroerd en klasse2ongeroerd)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#235]
## Type issue
realisatie

## Waar
textuur organische grond (attribuut van Grond)

## Samenvatting
Schrijffout in regel bij verwijzing naar waarde.

## Gerelateerd issue
#127 textuur organische grond voor QM5 (geroerd)

## Beschrijving
CamelCase niet goed toegepast in regel bij klasse2Geroerd en klasse2Ongeroerd. Moet zijn klasse2geroerd en klasse2ongeroerd.

## Oplossingsrichting
verbetering regel

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
