### ISSUE TITLE
twee classificaties TextuurOrganischeGrond

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#236]
## Type issue
standaardisatie

## Waar
textuurOrganischeGrond (waardelijst)

## Samenvatting
twee classificaties voor 1 gegeven

## Beschrijving
Het gegeven kent 2 classificaties (14688 en 5104). Dit onderscheid moet op eenduidige en heldere wijze worden aangebracht.  

## Oplossingsrichting
verbetering omschrijving waarden

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
