### ISSUE TITLE
kalkgehalteklasse bij kalkrijke gesteenten

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#237]
## Type issue
standaardisatie geologisch booronderzoek

## Waar
kalkgehalteklasse (attribuut van Gesteente)

## Samenvatting
kalkgehalteklasse bij kalkrijke gesteenten (kalksteen en mergel)

## Beschrijving
Hoe ga je om met gesteenten waarbij kalk per definitie aanwezig is (bij kalksteen en mergel).

## Oplossingsrichting
aanpassing kardinaliteit en regel

**Comment by fterpstra** [comment]
Besloten is dit niet aan te passen,
