### ISSUE TITLE
gezuiverdWater als overkoepelende term (GebruiktMedium)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#238]
## Type issue
standaardisatie

## Waar
GebruiktMedium (waardelijst)

## Samenvatting
gedestilleerdWater niet de goed naam

## Beschrijving
gedestilleerd water is niet de goede naam als overkoepelende term voor gedestilleerd, gedemineraliseerd of gedeinoniseerd water. Daarnaast is het niet onderscheidend van gedestilleerdWater (als gedestilleerd water).

## Oplossingsrichting
aanpassing naam (naar gezuiverdWater)

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
