### ISSUE TITLE
eenheid geleidbaarheid zoutwater (GebruiktMedium)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#239]
## Type issue
standaardisatie

## Waar
GebruiktMedium (waardelijst)

## Samenvatting
Verkeerde eenheid elektrische geleidbaarheid in omschrijving zoutwater.

## Beschrijving
De eenheid van elektrische geleidbaarheid bij zoutwater moet uS/cm ipv mS/cm.

## Oplossingsrichting
Aanpassing omschrijving waarden

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
