### ISSUE TITLE
Aanlevering

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#24]
P3.8 alinea 1:

zinsdeel: "...In hun geheel, dus een booronderzoek kan niet eerder aangeleverd worden dan nadat de definitieve resultaten van alle deelonderzoeken zijn vastgelegd...."

Hoe verhoudt dit zich tot de leveringsverplichting binnen 20 dagen?

**Comment by fterpstra** [comment]
Ga ik bespreken met de jurist van het programma BRO.
