### ISSUE TITLE
nieuwe coordinaattransformatiemethode RDNAPTRANS 2018

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#240]
## Type issue
standaardisatie

## Waar
Coördinaattransformatie (waardelijst)

## Samenvatting
Het NSGI heeft een nieuwe coordinaattransformatiemethode uitgebracht, RDNAPTRANS 2018.

## Beschrijving
Het NSGI heeft een nieuwe coordinaattransformatiemethode uitgebracht (RDNAPTRANS 2018). De BRO maakt bij het bereken van de gestandaardiseerde locatie gebruik van RDNAPTRANS (momenteel versie 2008). Tot 1 oktober 2020 magde oude versie RDNAPTRANS™2008 nog gebruikt worden.

## Oplossingsrichting
Toevoegen waarden

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
