### ISSUE TITLE
eigenschappen bij QM1-3 (interne structuur intact) onder klasse 3

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#241]
## Type issue
implementatie

## Waar
interne structuur intact (attribuut van Laag)

## Samenvatting
Discrepanties tussen de norm en de BRO wanneer eigenschappen onder klasse 3 worden beschreven wanneer de interne structuur van de laag intact is (QM1-3).

## Beschrijving
Een aantal eigenschappen worden beschreven wanneer de interne structuur intact is (QM1-3). Voor klasse 3 worden deze eigenschappen in de praktijk meestal niet beschreven, maar het kan voorkomen dat de eigenschappen worden beschreven. In de BRO bestaat voor deze gegevens vrijheid van keuze. De vrijheid van keuze voor klasse 3 staat eenmalig op het niveau van het attribuut interne structuur intact. De bovengenoemde eigenschappen die worden beschreven wanneer de interne structuur intact is, zijn afhankelijk van het gegeven interne structuur intact.

## Oplossingsrichting
aanpassing regels.

**Comment by fterpstra** [comment]
In het correctieblad NEN14688 zijn een aantal wijzigingen doorgevoerd die betrekking hebben op het al dan niet verplicht vastleggen van bepaalde aspecten bij de beschrijving van grond. De gevolgen voor de verkennende klasse 3 beschrijvingen was niet helder. Nieuwe afspraak met de NEN commissie is dat er geen vrijheden onder klasse 3 beschrijvingen bestaan, zodat er in de praktijk ook een verschil tussen klasse 2 en klasse 3 beschrijvingen bestaat zoals de norm bedoeld. Dat betekent dat een aantal gegevens niet mag worden vastgelegd onder klasse 3 waaronder dit gegeven.
