### ISSUE TITLE
bijzonder bestanddeel onder klasse 3

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#242]
## Type issue
implementatie

## Waar
bijzonder bestanddeel (attribuut van Grond)

## Samenvatting
Discrepantie tussen de BRO en de norm voor klasse 3

## Beschrijving
Aanpassing norm (correctieblad) bijzonder bestanddeel verplicht voor klasse 3, behalve voor organische gronden.

## Oplossingsrichting
aanpassing regel

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
