### ISSUE TITLE
kalkgehalteklasse onder klasse 3 (keuzevrijheid)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#243]
## Type issue
standaardisatie

## Waar
kalkgehalteklasse (attribuut van Grond)

## Samenvatting
kalkgehalteklasse keuzevrijheid voor klasse 3

## Gerelateerd issue
#227 kalkgehalteklasse onder klasse 3

## Beschrijving
Het beschrijven van de kalkgehalteklasse is voor klasse 3 niet  verplicht. Er is vrijheid van keuze. De regel is te streng.

## Oplossingsrichting
aanpassing regel

**Comment by fterpstra** [comment]
In het correctieblad NEN14688 zijn een aantal wijzigingen doorgevoerd die betrekking hebben op het al dan niet verplicht vastleggen van bepaalde aspecten bij de beschrijving van grond. De gevolgen voor de verkennende klasse 3 beschrijvingen was niet helder. Nieuwe afspraak met de NEN commissie is dat er geen vrijheden onder klasse 3 beschrijvingen bestaan, zodat er in de praktijk ook een verschil tussen klasse 2 en klasse 3 beschrijvingen bestaat zoals de norm bedoeld. Dat betekent dat een aantal gegevens niet mag worden vastgelegd onder klasse 3 waaronder dit gegeven.
