### ISSUE TITLE
Bepaling maximale ongedraineerde schuifsterkte

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#244]
## Type issue
Publieke consultatie

## Van
Wiertsema en Partners

## Waar
3.38 Bepaling maximale ongedraineerde schuifsterkte

## Beschrijving
Heeft kardinaliteit [0..1]. Is het een expliciete keuze geweest om geen handvinproef en penetroproef op hetzelfde onderzocht interval te kunnen doen? Het zijn verschillende methoden waar dezelfde parameter uit bepaald kan worden. In principe is het mogelijk om binnen de minimale lengte van het interval hiervoor (5cm) beiden bepalingen uit te voeren (de 2 á 3 resultaten die nodig zijn tot de parameter te komen). Als het geen expliciete keuze is geweest om de kardinaliteit op [0..1] te zetten, zou dit wellicht op [0..2] gezet kunnen worden om beide methode op hetzelfed interval toe te staan.

**Comment by fterpstra** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
