### ISSUE TITLE
gebruikt medium (waterdoorlatendheid)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#245]
## Type issue
Publieke consultatie

# Van
Wiertsema en Partners

## Waar
3.68.10 Gebruikt medium (waterdoorlatendheid)

## Beschrijving
Er wordt geen selectie gehanteerd welke waarden uit de codelijke MediumGebruikt toegstaan zijn. Houdt dit in dat in theorie een waterdoorlatendheid met een ingevuld medium 'helium' of 'butanol' gewoon gevalideerd kunnen worden?
Ditzelfde geldt voor de verschillende voorkomens van BijzonderheidUitvoering en Stopcriterium. In de werkversie 0.99 waren de keuzes nog beperkt tot bijzonderheden die bij die bepaling horen, nu is deze beperking weg. Naar mijn idee levert dit een risico op waarbij ongerelateerde waarden gewoon gevalideerd kunnen worden.

**Comment by fterpstra** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
