### ISSUE TITLE
maakmethode (waterdoorlatendheid)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#246]
## Type issue
Publieke consultatie

## Van
Wiertsema en Partners

## Waar
3.36.4 maakmethode (waterdoorlatendheid)

## Beschrijving
alleen kneden/samenstellenStrooienDroog zijn toegestaan. Dit levert een beperkte range van droge volumieke massa's op. Wanneer een waterdoorlatendheid bepaald moet worden bij proctordichtheid, zal de maakmethode bijvoorbeeld ook stampenProctor of samenstellenStampenDroog kunnen zijn.

**Comment by fterpstra** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de verwerking van de publieke consultatie, zie https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-gt.xlsx voor de verwerking en zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
