### ISSUE TITLE
foto bij triaxiaal en DSS

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#248]
## Type issue
Review sessie

## Van
VOTB werkgroep geotechnische laboratoria

## Samenvatting
Het opnemen van foto's bij de triaxiaal en dss is essentieel.

## Beschrijving
Foto’s worde pas opgepakt bij boormonsterfotografie. De foto is essentieel voor het gebruik van de resultaten. De verwachting is dat gebruiker gaat bellen voor de foto zolang deze niet in de BRO is geborgd. 

## Oplossingsrichting
Een voorstel voor een tijdelijke centrale voorziening (zolang boormonsterfotografie nog niet in de BRO is opgenomen) ligt bij het programmabureau.

**Comment by fterpstra** [comment]
Er komt een voorziening voor het uploaden van boormonsterfotos in de catalogus versie 1.99 is daar rekening mee gehouden
