### ISSUE TITLE
Bepaling verticale vervorming vs Bepaling zettingseigenschappen

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#249]
## Type issue
Reviewsessie

## Van
Fugro

## Waar
Bepaling verticale vervorming vs Bepaling zettingseigenschappen

## Beschrijving
Bijgevoegde twee domeinmodeluitsneden verschillen (op sommige aspecten aanzienlijk) van elkaar. Als gevolg daarvan reizen bij ons de vragen:

•	Wat is de reden dat de proef ‘verticale vervorming’ ‘in tweeën wordt geknipt’ wat betreft BRO opname en men niet heeft gewacht met de volledige opname van de proef tijdens de volgende fase? Wat dat betreft past de bepaling ‘verticale vervorming’ ons inziens ook beter bij de overige, nog te volgen overwegend mechanische proeven / sterkteproeven (fase 1, oftewel catalogus van 15-april-2019, lijkt zich over het algemeen toch meer te richten op monsterbeschrijving / classificatietesten, zoals watergehalte, org. stof gehalte, kalkgehalte, volumegewicht, volumieke massa vaste delen en korrelverdeling)
•	Zijn er meer bepalingen die op deze wijze ‘in tweeën’ zijn geknipt en over twee fasen verspreid in de BRO worden opgenomen?

**Comment by fterpstra** [comment]
Dit issue is verwerkt in de 1.99 versie van de catalogus zie : https://basisregistratieondergrond.nl/publish/library/265/catalogus_geotechische_boormonsterbeschrijving_en_analyse_v1_99_docx.pdf voor de resulterende catalogus.
