### ISSUE TITLE
omschrijving kardinaliteit [...]

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#25]
P4.3 alinea 2/3:

Zinsdeel:"...opgenomen. Het onderstaande overzicht geeft de vier mogelijkheden die voorkomen."

Klopt het dat onderstaande opsomming nog moet worden herzien?
Tussen [...] is namelijk gelijk, maar tekst er achter is anders!

**Comment by fterpstra** [comment]
Het gaat niet alleen om de [...] maar de combinatie met het aanwezig zijn van regels. Die combinatie verschilt voor iedere mogelijkheid, tekst is correct
