### ISSUE TITLE
algemeen - afleidbare gegevens: naam gebeurtenis

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#250]
## Type issue
Standaardisatie

## Waar
naam gebeurtenis (attribuut van Tussentijdse gebeurtenis)

## Samenvatting
naam gebeurtenis is geen afleidbaar gegeven (maar gegenereerd)

## Beschrijving
Afleidbare gegevens zijn gegevens die afleidbaar zijn uit andere gegevens (attributen en relaties) binnen het domeinmodel (MIM). Afleidbare gegevens worden bij uitzondering opgenomen en worden in de catalogus aangeduid met Is afgeleid.

## Oplossingsrichting
naam gebeurtenis is niet afgeleid

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
