### ISSUE TITLE
algemeen - afleidbare gegevens: coördinaten (Gestandaardiseerde locatie)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#251]
## Type issue
Standaardisatie

## Waar
coördinaten (attribuut van Gestandaardiseerde locatie)

## Samenvatting
coördinaten is een afleidbaar gegeven

## Beschrijving
Afleidbare gegevens zijn gegevens die afleidbaar zijn uit andere gegevens (attributen en relaties) binnen het domeinmodel (MIM). Afleidbare gegevens worden bij uitzondering opgenomen en worden in de catalogus aangeduid met Is afgeleid.

## Oplossingsrichting
coördinaten is afgeleid

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
