### ISSUE TITLE
herstel volgorde attributen Booronderzoek

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#252]
## Type issue
standaardisatie

## Waar
Booronderzoek (entiteit)

## Samenvatting
De attributen zijn in de catalogus v1.9 (31-okt-2019) door elkaar geraakt.

## Beschrijving
De volgorde van attributen in catalogus v1.9 (31-okt-2019) is anders dan de volgorde in catalogus v0.99 (15-april-2019)

## Oplossingsrichting
De volgorde herstellen conform catalogus v0.99 (15-april-2019)

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
