### ISSUE TITLE
BijzonderBestanddeel vs SoortBijzonderBestanddeel

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#253]
## Type issue
standaardisatie

## Waar
bijzonder bestanddeel (attribuut van Onderzocht materiaal) en 
bijzonder bestanddeel (attribuut van Grond).

## Samenvatting
Waardelijst hergebruiken, BijzonderBestanddeel (waardelijst) wordt SoortBijzonderBestanddeel

## Beschrijving
De waardelijst BijzonderBestanddeel (geotechniek) en SoortBijzonderBestanddeel (geologie) hebben dezelfde inhoud maar een andere naam. De correcte naam is SoortBijzonderBestanddeel

## Oplossingsrichting
De naam van de waardelijst BijzonderBestanddeel (TertiaryConstituent) aanpassen naar SoortBijzonderBestanddeel (ParticularConstituentType)

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
