### ISSUE TITLE
naamgeving cementsoort vs soort cement

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#254]
## Type issue
standaardisatie

## Waar
cementsoort (attribuut van Gesteente)

## Samenvatting
Naam in lijn brengen, cementsoort wordt soort cement (met waardelijst SoortCement)

## Beschrijving
De nederlandse naam cementsoort is niet in lijn met de namen van andere soorten materiaal (engels onveranderd).

## Oplossingsrichting
cementsoort (cementType) wordt soort cement (cementType) met waardelijst SoortCement (CementType)

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
