### ISSUE TITLE
aanpassing beschrijfprocedure 14688-1 (correctieblad)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#255]
## Type issue
Standaardisatie

## Waar
Beschrijfprocedure (waardelijst)

## Samenvatting
Nieuw correctieblad bij 14688-1

## Beschrijving
De NEN-commissie gaat een nieuw correctieblad met wijzigingen op de 14688-1: 2019 uitgeven.

## Oplossingsrichting
aanpassing waarde 14688d1v2019

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
