### ISSUE TITLE
treksterkte veen voor QM4

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#256]
## Type issue
implementatie

## Waar
treksterkte veen (attribuut van Grond)

## Samenvatting
Discrepantie tussen de BRO en de norm voor QM4

## Beschrijving
In de BRO wordt treksterkte veen voor QM4 vastgelegd, in de norm niet. 

## Oplossingsrichting
aanpassing regel, treksterkte veen wordt niet vastgelegd voor QM4

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
