### ISSUE TITLE
geotechnische afzettingskarakteristiek vs afzettingskarakteristiek

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#257]
## Type issue
standaardisatie

## Waar
geotechnische afzettingskarakteristiek (attribuut van Grond)
GeotechnischeAfzettingskarakteristiek (waardelijst)

## Samenvatting
Waardelijst hergebruiken,  GeotechnischeAfzettingskarakteristiek (waardelijst) wordt Afzettingskarakteristiekattribuut en geotechnische afzettingskarakteristiek (attribuut) wordt afzettingskarakteristiek

## Beschrijving
De waardelijsten Afzettingskarakteristiek (BHR-P), bodemkundigeAfzettingskarakteristiek (SFR) en geotechnischeAfzettingskarakteristiek (BHR-GT) hebben dezelfde inhoud maar een andere naam. De correcte naam is Afzettingskarakteristiek.

## Oplossingsrichting
Aanpassing naam waardelijst van GeotechnischeAfzettingskarakteristiek (GeotechnicalDepositionalCharacteristic) naar Afzettingskarakteristiek (DepositionalCharacteristic) en attribuut van geotechnische afzettingskarakteristiek (geotechnicalDepositionalCharacteristic) naar afzettingskarakteristiek (depositionalCharacteristic)

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
