### ISSUE TITLE
Post-sedimentaire discontinuiteit voor QM4

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#258]
## Type issue
implementatie

## Waar
Post-sedimentaire discontinuiteit (entiteit)

## Samenvatting
Discrepantie tussen de BRO en de norm voor QM4.

## Gerelateerd issue
#241 interne structuur intact onder klasse 3

## Beschrijving
Post-sedimentaire discontinuiteit verplicht wanneer interne structuur intact (QM1-QM3).
Aanpassing norm (correctieblad): voor klasse 3 wordt deze eigenschap niet beschreven. In de BRO bestaat voor dit gegeven vrijheid van keuze. De vrijheid van keuze voor klasse 3 staat op het niveau van het attribuut interne structuur intact.

## Oplossingsrichting
aanpassing regel, Post-sedimentaire discontinuiteit verplicht wanneer interne structuur intact (QM1-3) en optioneel voor klasse 3 (via interne structuur intact).

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
