### ISSUE TITLE
gelaagd voor QM4

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#259]
## Type issue
implementatie

## Waar
gelaagd (attribuut van Laag)

## Samenvatting
Discrepantie tussen de BRO en de norm voor QM4.

## Gerelateerd issue
#241 interne structuur intact onder klasse 3

## Beschrijving
gelaagd verplicht wanneer interne structuur intact (QM1-QM3).

## Oplossingsrichting
aanpassing regel, gelaagd verplicht wanneer interne structuur intact (QM1-3).

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
