### ISSUE TITLE
codelijst 6.0.16 bemonsteringsprocedure

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/BHR-GT#26]
Pagina 68 van 182, 6.0.16 bemonsteringsprocedure:

Dit is een verplicht veld waarbij wordt toegelicht dat de procedure een norm, protocol, richtlijn kan zijn. Echter geeft de codelijst maar 1 mogelijkheid, namenlijk ISO22475D1v2006.

**Comment by fterpstra** [comment]
Antwoord Robert-Jan van Leeuwen:
"Correct, maar dat betekent niet dat er in de toekomst geen nieuwe waarden kunnen ontstaan, en daar moet op worden geanticipeerd."
