### ISSUE TITLE
Post-sedimentaire discontinuiteit onder klasse 3

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#260]
## Type issue
implementatie

## Waar
Post-sedimentaire discontinuiteit (entiteit)

## Samenvatting
Post-sedimentaire discontinuiteit onder klasse 3 optioneel

## Beschrijving
Aanpassing norm (correctieblad): voor klasse 3 wordt deze eigenschap niet beschreven. In de BRO bestaat voor dit gegeven vrijheid van keuze. De vrijheid van keuze voor klasse 3 staat op het niveau van het attribuut interne structuur intact.

## Oplossingsrichting
Post-sedimentaire discontinuiteit optioneel voor klasse 3 (via interne structuur intact).

**Comment by fterpstra** [comment]
In het correctieblad NEN14688 zijn een aantal wijzigingen doorgevoerd die betrekking hebben op het al dan niet verplicht vastleggen van bepaalde aspecten bij de beschrijving van grond. De gevolgen voor de verkennende klasse 3 beschrijvingen was niet helder. Nieuwe afspraak met de NEN commissie is dat er geen vrijheden onder klasse 3 beschrijvingen bestaan, zodat er in de praktijk ook een verschil tussen klasse 2 en klasse 3 beschrijvingen bestaat zoals de norm bedoeld. Dat betekent dat een aantal gegevens niet mag worden vastgelegd onder klasse 3 waaronder dit gegeven.
