### ISSUE TITLE
scheefstaand vanaf 15 graden

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#262]
## Type issue
implementatie

## Waar
scheefstaand (attribuut van Laag)

## Samenvatting
scheefstaand bij meer dan 15% scheef

## Beschrijving
In het correctieblad is aangegeven dat een laag scheefstaand is wanneer de laag meer dan 15% scheef staat. 

## Oplossingsrichting
aanpassing toelichting

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
