### ISSUE TITLE
bijzonder bestanddeel voor organische gronden

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#263]
## Type issue
implementatie

## Waar
bijzonder bestanddeel (attribuut van Grond)

## Samenvatting
bijzonder bestanddeel niet voor organische gronden

## Beschrijving
Aanpassing norm (correctieblad) bijzonder bestanddeel wordt niet vastgelegd voor organische gronden.

## Oplossingsrichting
aanpassing regel

**Comment by fterpstra** [comment]
foutieve aanname, In de norm worden twee termen door elkaar gebruikt wat leidt tot verwarring (tertiaire bestanddelen en bijzondere bestanddelen). Organische gronden toch niet uitgesloten.
