### ISSUE TITLE
lensjes (disperse inhomogeniteit) alleen in-situ

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#264]
## Type issue
Publieke consultatie/Review sessie [verwijderen wat niet van toepassing is]

## Waar
[Geef aan over welke plek in het document de melding gaat. Bijvoorbeeld: 'Paragraaf x.x', 'pagina y'.]

## Samenvatting
[Korte tekst van de melding. Bijvoorbeeld: 'De tekst is hier onduidelijk.']

## Beschrijving
[Lange omschrijving van de melding. Probeer zo concreet mogelijk het probleem of je suggestie voor verbetering te beschrijven. Bijvoorbeeld: 'Het is onduidelijk wat er precies met ... bedoeld wordt'.]

## Oplossingsrichting
[Geef een suggestie voor een oplossing, in de vorm van een tekstvoorstel of een oplossingsrichting.]

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
