### ISSUE TITLE
bijzonderheid uitvoering [0..2]

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#265]
## Type issue
reviewsessie

## Waar
bijzonderheid uitvoering (attribuut van Bepaling zettingseigenschappen)
bijzonderheid uitvoering (attribuut van Bepaling korrelgrootteverdeling)
bijzonderheid uitvoering (attribuut van Bepaling watergehalte)
bijzonderheid uitvoering (attribuut van Bepaling volumieke massa)
bijzonderheid uitvoering (attribuut van Bepaling volumieke massa vaste delen)
bijzonderheid uitvoering (attribuut van Bepaling organischestofgehalte)
bijzonderheid uitvoering (attribuut van Bepaling kalkgehalte)

## Samenvatting
mogelijkheid tot vastleggen twee bijzonderheden

## Beschrijving
De mogelijkheid faciliteren om twee bijzonderheden vast te leggen.

## Oplossingsrichting
aanpassing kardinaliteit naar [0..2]

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
