### ISSUE TITLE
bijzonderheid uitvoering geen controle op waarden

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#266]
## Type issue
standaardisatie

## Waar
bijzonderheid uitvoering (attribuut van Bepaling zettingseigenschappen)
bijzonderheid uitvoering (attribuut van Bepaling korrelgrootteverdeling)
bijzonderheid uitvoering (attribuut van Bepaling watergehalte)
bijzonderheid uitvoering (attribuut van Bepaling volumieke massa)
bijzonderheid uitvoering (attribuut van Bepaling volumieke massa vaste delen)
bijzonderheid uitvoering (attribuut van Bepaling organischestofgehalte)
bijzonderheid uitvoering (attribuut van Bepaling kalkgehalte)

## Samenvatting
geen controle op toegestane waarden

## Beschrijving
De lijst wordt in meerdere bepalingen gebruikt. De lijst is nog niet stabiel en in ontwikkeling. 

## Oplossingsrichting
regels

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
