### ISSUE TITLE
vacuumconsolidatie (ipv vacuümconsolidatie)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#267]
## Type issue
realisatie

## Waar
Voorbereiding (waardelijst) en
einddiepte voorbereiding (attribuut van Boring)

## Samenvatting
vacuumconsolidatie (ipv vacuümconsolidatie)

## Beschrijving
Er mogen geen bijzondere tekens voorkomen in waarden van waardelijsten. Waarde  moet zijn Vacuumconsolidatie (ipv vacuümconsolidatie)

## Oplossingsrichting
waarde aanpassen naar vacuumconsolidatie (in waardelijst en regel)

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
