### ISSUE TITLE
waardebereik verlopen tijd (Zettingstoestand, was Verticale vervorming) niet correct

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#268]
## Type issue
realisatie

## Waar
verlopen tijd (attribuut van Zettingstoestand, was Verticale vervorming)

## Samenvatting
waardebereik verlopen tijd niet correct

## Beschrijving
Minimum moet 0 zijn ipv 430000.

## Oplossingsrichting
aanpassing waardebereik

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
