### ISSUE TITLE
waardebereik verticale rek (Zettingstoestand) niet correct

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#269]
## Type issue
standaardisatie

## Waar
verticale rek (attribuut van Zettingstoestand, was Verticale vervorming)

## Samenvatting
waardebereik verticale rek niet correct

## Beschrijving
Minimum moet -1 zijn ipv 0. Het proefstuk kan zwellen.

## Oplossingsrichting
aanpassing waardebereik

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
