### ISSUE TITLE
Fout in regel bij Bepaling maximale ongedraineerde schuifsterkte

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#270]
## Type issue
realisatie

## Waar
Bepaling maximale ongedraineerde schuifsterkte (entiteit)

## Samenvatting
regel niet correct

## Beschrijving
De entiteit mag niet  aanwezig zijn in alle andere gevallen. Er tond ‘in andere gevallen is het gegeven aanwezig’.

## Oplossingsrichting
verbetering regel

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
