### ISSUE TITLE
schrijffout in regel bij bepalingsmethode van Bepaling korrelrootteverdeling (ISO17892d4v2016enISO13317d3v2001)

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#271]
## Type issue
realisatie

## Waar
bepalingsmethode (Attribuut van Bepaling korrelgrootteverdeling)

## Samenvatting
Schrijffout in regel bij verwijzing naar waarde

## Beschrijving
waarde in regel (ISO13317d3v2001en17892d4v2016) moet zijn ISO17892d4v2016enISO13317d3v2001 

## Oplossingsrichting
verbetering regel, moet zijn ISO17892d4v2016enISO13317d3v2001

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
