### ISSUE TITLE
domein meetwaarde equivalente massa

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#272]
## Type issue
reviewsessie

## Waar
equivalente massa (attribuut van Bepaling korrelgrootteverdeling)

## Samenvatting
Foutief domein (eenheid) meetwaarde

## Beschrijving
Correctie domein Meetwaarde: gram/kubieke centimeter (ipv procent). De opbouw en eenheid van de meetwaarde veranderen mee.

## Oplossingsrichting
aanpassing domein naar gram/kubieke centimeter (en opbouw 1.4 en waardebereik 0 tot 4)

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
