### ISSUE TITLE
equivalente massa is geen correcte term

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#273]
## Type issue
reviewsessie

## Waar
equivalente massa (attribuut van Bepaling korrelgrootteverdeling)

## Samenvatting
De term equivalente massa klopt niet. 

## Beschrijving
De term equivalente massa klopt niet. Het is geen equivalente massa. 

## Oplossingsrichting
aanpassing naam

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
