### ISSUE TITLE
Bereik fracties van de basisverdeling te krap

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#274]
## Type issue
reviewsessie

## Waar
fractie kleiner63um (attribuut van Basis korrelgrootteverdeling) en
fractie groter63um (attribuut van Basis korrelgrootteverdeling)

## Samenvatting
Bereik van 99.9 is te krap

## Beschrijving
Een bereik van 99.9 is te krap, de fractie kan 100% zijn.

## Oplossingsrichting
aanpassing opbouw meetwaarde naar 1.3 (en bijbehorend waardebereik naar 100%)

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
