### ISSUE TITLE
fractiegrens 710 um in uitgebreide verdeling

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#275]
## Waar
fractie 500tot710um (attribuut van Uitgebreide verdeling fractie groter63um)
fractie 710tot1000um (attribuut van Uitgebreide verdeling fractie groter63um)

## Samenvatting
Fractiegrens in de uitgebreide verdeling verkeerd, moet zijn 710 (ipv 630)

## Beschrijving
In de gegevensdefinitie staat in de uitgebreide verdeling 630 um als fractiegrens ipv 710 um. In het domeinmodel staat het wel goed en in de standaardverdeling staat het ook goed. 

## Oplossingsrichting
verbetering naam naar fractie 500tot710um en fractie 710tot1000um

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
