### ISSUE TITLE
stopcriterium voor veld en lab

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#276]
## Type issue
standaardisatie

## Waar
stopcriterium (attribuut van Boring)
stopcriterium (attribuut van Bepaling schuifspanningsverloop bij belasting)
stopcriterium (attribuut van Bepaling schuifspanningsverloop bij horizontale vervorming)
Stopcriterium (waardelijst)

## Samenvatting
splitsen waardelijst stopcriterium

## Beschrijving
Lijst met dezelfde naam wordt binnen BHR-GT gebruikt voor verschillende stopcriteria.

## Oplossingsrichting
Waardelijst splitsen in StopcriteriumLab en StopcriteriumVeld

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
