### ISSUE TITLE
naamgeving gesteentesoort vs soort gesteente

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#277]
## Type issue
standaardisatie

## Waar
gesteentesoort (attribuut van Gesteente), wordt soort gesteente
Gesteentesoort (waardelijst), wordt SoortGesteente

## Samenvatting
Naam in lijn brengen, gesteentesoort wordt soort gesteente (met waardelijst SoortGesteente)

## Beschrijving
De nederlandse naam gesteentesoort is niet in lijn met de namen van andere soorten materiaal (engels onveranderd).

## Oplossingsrichting
naam in lijn brengen met andere soorten, naar soort gesteente (engels onveranderd)

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
