### ISSUE TITLE
naamgeving veensoort vs soort veen

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#278]
## Type issue
standaardisatie

## Waar
veensoort (attribuut van Grond), wordt soort veen
Veensoort (waardelijst), wordt SoortVeen

## Samenvatting
Naam in lijn brengen, veensoort wordt soort veen (met waardelijst SoortVeen)

## Beschrijving
De nederlandse naam veensoort is niet in lijn met de namen van andere soorten materiaal (engels onveranderd).

## Oplossingsrichting
naam in lijn brengen met andere soorten, naar soort veen (engels onveranderd)

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
