### ISSUE TITLE
Gebruik van XSD

### ISSUE THREAD

**Issue by ArdtK** [BROprogramma/BHR-GT#280]
## Type issue
Publieke consultatie

## Waar
Algemeen gebruik XSD

## Samenvatting
Hoe kunnen we de XSD gebruiken om een valide XML te maken?

## Beschrijving
Bij de ontwikkeling vanuit Deltares lopen we tegen een aantal vragen aan:

1. Hoe kunnen we een XML valideren? In de voorbeeld XML bestanden staat de locatie van de XSD niet aangegeven.
2. Hoe kunnen we toegang krijgen tot de URLs waar XSD’s staan? Waarschijnlijk hebben we een certificaat nodig.
3. Hoe kunnen we de namen van de elementen bepalen? In de voorbeelden staan Engelse elementnamen terwijl in de catalogus alles in het Nederlands is.

## Oplossingsrichting
Kunnen we een keer bellen/Skypen oid?

**Comment by fterpstra** [comment]
Beste Ardt,
Ik ga je in contact brengen met onze ketentest manager. Daarnaast het vriendelijke verzoek om je vragen ook in te schieten bij de BRO servicedesk https://basisregistratieondergrond.nl/servicepagina/formulieren/contactformulier/
Dan kunnen zij meelezen en mogelijk in de toekomst anderen met dezelfde vragen makkelijker helpen.
vriendelijke groeten
Frank Terpstra

**Comment by ArdtK** [comment]
Dag Frank,

Dat je wel, ik wacht het af.
Ik heb de vragen inmiddels ook ingediend bij de servicedesk.

Groet,
Ardt
+31 6 46254775
