### ISSUE TITLE
Waardebereik GHG en GLG

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#281]
## Type issue
standaardisatie geologisch booronderzoek

## Waar
gemiddeld hoogste grondwaterstand (attribuut van Boorprofiel)
gemiddeld laagste grondwaterstand (attribuut van Boorprofiel)

## Samenvatting
Waardebereik niet in overeenstemming met geologisch booronderzoek.

## Beschrijving
In geotechniek wordt een maximum van 50 gehanteerd en bij geologie een maximum van 100 m. 

## Oplossingsrichting
Aanpassen waardebereik naar maximaal 100 meter

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
