### ISSUE TITLE
plaatsing specifieke indeling voor filterstrookjes

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#282]
## Type issue
standaardisatie

## Waar
plaatsing (attribuut van Filterstrookcorrectie) 
Plaatsing (waardelijst) wordt PlaatsingFilterstrook

## Samenvatting
Lijst met algemene naam maar geen gestandaardiseerde indeling. 

## Beschrijving
Plaatsing is een algemeen gegeven dat herbruikbaar zou moeten zijn. De betreffende lijst is een specifieke indeling van plaatsing, namelijk voor filterstrookjes. 

## Oplossingsrichting
Waardelijst specifiek maken bij naam: PlaatsingFilterstrook

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
