### ISSUE TITLE
 lagerwrijvingcorrectie vs schuiflagercorrectie toegepast

### ISSUE THREAD

**Issue by BregjeBrugman** [BROprogramma/BHR-GT#283]
## Type issue
standaardisatie

## Waar
schuiflagercorrectie toegepast (attribuut van Bepaling schuifspanningsverloop bij horizontale vervorming)

## Samenvatting
Een gegeven heeft verschillende namen in bepalingen.

## Beschrijving
Schuiflagercorrectie is hetzelfde als lagerwrijvingcorrectie bij Bepaling zettingseigenschappen.

## Oplossingsrichting
aanpassing naam, wordt: lagerwrijvingcorrectie toegepast

**Comment by adbgnm** [comment]
Dit issue is verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor catalogus https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
