### ISSUE TITLE
Grindmediaanklasse 5104 vs 14688

### ISSUE THREAD

**Issue by JPietersen** [BROprogramma/BHR-GT#284]
## Type issue
Implementatie

## Waar
Codelijst 1.48 Grindmediaanklasse

## Samenvatting
Huidige waarden codelijst Grindmediaanklasse zijn wegens de klassegrenzen niet te gebruiken voor 14688.

## Beschrijving
De omschrijvingen in Grindmediaanklasse hebben betrekking op NEN5104, de grenzen tussen fijn/middelgrof/grof  grind in ISO14688 zijn anders.

## Oplossingsrichting
Wijzigen waarden voor NEN5104 (IMBRO/A) met toevoeging 'NEN5104':
fijnNEN5104: 2 tot 5.6 mm
middelgrofNEN5104: 5.6 - 16 mm
grofNEN5104: 16 - 63 mm

Toevoegen waarden voor ISO14688:
fijn: 2 tot 6.3 mm
middelgrof: 6.3 tot 20 mm
grof: 20 - 63 mm

**Comment by BregjeBrugman** [comment]
Nogmaals dank voor uw reactie. Dit issue is meegenomen in de Werkafspraak BHR-GT tranche 2. De werkafspraak tranche 2 is in zijn geheel verwerkt in de catalogus voor tranche 3 Catalogus booronderzoek: geotechnische boormonsteranalyses en beschrijvingen. Zie voor de werkafspraak en de catalogus: https://basisregistratieondergrond.nl/werken-bro/producten-diensten/standaarden/catalogi/.
