### ISSUE TITLE
Samengestelde lagen

### ISSUE THREAD

**Issue by JPietersen** [BROprogramma/BHR-GT#285]
## Type issue
Implementatie

## Waar
Gelaagdheid (3.21.12) en Gelaagde inhomogeniteit (3.22.8)

## Samenvatting
Bij samengestelde lagen is het niet mogelijk de beide laagdiktes van de samengestelde laag te beschrijven.

## Beschrijving
Gelaagdheid (betrekking op Laag) mag niet aanwezig zijn wanneer Samengestelde laag gelijk is aan 'Ja'.
Wanneer ik uit de NEN-EN-ISO 14688-1 de beschrijving 'KLEI, (…), dun gelaagd met weinig dunne zand laminae' beschouw, is Samengestelde laag gelijk aan 'Ja'. Gelaagdheid binnen 'Laag' kan nu dus niet ingevuld worden. Het resultaat in de BRO is 'KLEI, (…), met weinig dunne zand laminae' (zandWeinigDunneLaminae).

## Oplossingsrichting
Wanneer Gelaagd J/N bepaalt of Gelaagdheid wel of niet aanwezig mag zijn, en Samengestelde laag J/N bepaalt of Gelaagde inhomogeniteit aanwezig mag zijn, kan een samengestelde laag zoals hierboven beschreven wel opgenomen worden in de BRO.

**Comment by BregjeBrugman** [comment]
De BRO is aangepast, gelaagdheid wordt nu ook vastgelegd van samengestelde lagen. De aanpassing is vastgelegd in werkafspraak versie 2.1, zie werkafsprakenlijst nr.12
https://bro-productomgeving.nl/bpo/latest/bodem-en-grondonderzoek/booronderzoek-bhr/geotechnisch-booronderzoek-bhr-gt/werkafspraak-geotechnisch-booronderzoek-tranche-3
