### ISSUE TITLE
Analyses kunnen aanleveren in meerdere keren/delen

### ISSUE THREAD

**Issue by BartJandeLeuw** [BROprogramma/BHR-GT#286]
## Samenvatting
Boorbedrijven geven aan dat zij verschillende analyses willen kunnen aanleveren in meerdere keren/delen bij het zelfde booronderzoek, om meerdere redenen, de voornaamste reden lijkt dat het in de tijd uit elkaar lopende analyses betreft waarvan bij de eerste aanlevering niet zeker is of/dat er nog meer analyses gaan worden toegevoegd. 

## Oplossingsrichting
Maak het makkelijk om alsnog analyses toe te voegen aan een booronderzoek dat eerder afgerond leek te zijn (dus zonder ingewikkelde correctieberichten voorafgaand aan de aanvulling met extra analyseresultaten).

**Comment by RuudMutsaers** [comment]
Reactie Mos Geo: We zijn nu een stuk verder in het proces en hebben de zaken geimplementeerd. Het wordt nu niet meer als een probleem ervaren en het aanvullen van een analyse kan altijd doormiddel van een corectie plaatsvinden. De behoefte is om hier iets in te wijzigen speelt nu niet meer!
