### ISSUE TITLE
TerreinToestand bepaald ten ontrechte indicatie "geen waarde"

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/BHR-GT#287]
## Type issue
Implementatie

## Waar
3.1.11

## Samenvatting
Er is een kopje aanwezig: "mogelijk geen waarde" "Ja". Dit is onterecht omdat de regel slechts spreekt van "het attribuut"

## Beschrijving
Mogelijk fout gegaan in omzetting naar MIM

## Oplossingsrichting
Omzetting aanpassen

**Comment by BregjeBrugman** [comment]
is een foutje in de 2.0 catalogus. Omdat versie 2.1 uit 1.1 plus werkafspraak bestaat is dit issue vervallen in versie 2.1.
