### ISSUE TITLE
IMBRO/A regels op einddiepte voorbereiding

### ISSUE THREAD

**Issue by weeginkjw** [BROprogramma/BHR-GT#288]
bevinding LV team, Catalogus BHR-GT

3.9.3        voorbereiding
3.9.4        einddiepte voorbereiding

De regels in V2 zijn anders (fout?) geformuleerd t.o.v. V1:

![image](https://user-images.githubusercontent.com/57102598/95312173-e2e57980-088e-11eb-99d5-8a9c7d59cbf0.png)

NB ze hebben een andere uitwerking als bij IMBRO/A de waarde ontbreekt:

![image](https://user-images.githubusercontent.com/57102598/95313003-e4637180-088f-11eb-8b3f-46fc7038a21d.png)

Ik neem aan dat de V1 uitwerking ook voor V2 moet gelden…

Oplossingsrichting: pas de regel aan zoals bedoeld in V1

**Comment by BregjeBrugman** [comment]
Is een (onbedoelde) fout in de 2.0 catalogus. Omdat versie 2.1 uit 1.1 plus werkafspraak bestaat is dit issue vervallen in versie 2.1.
