### ISSUE TITLE
Is 1 disperse inhomogeniteit voldoende?

### ISSUE THREAD

**Issue by MarcelReuvers** [BROprogramma/BHR-GT#5]
Vanuit geotechniek is gesteld dat er maar 1 disperse inhomogeniteit belangrijk is voor de geotechnische eigenschappen van de grond. De beschrijver maakt hier in de keuze. Is 1 inhomogeniteit voldoende?

**Comment by fterpstra** [comment]
In versie 0.9 verwerkt
