### ISSUE TITLE
Regels m.b.t. omschrijving veensoort onjuist

### ISSUE THREAD

**Issue by ArthurDeMoel** [BROprogramma/BHR-GT#9]
In paragraaf 9.3.16 (attr. veensoort pag. 113/114) van de BRO-catalogus staat bij 'Regels':
_Het gegeven is aanwezig wanneer de waarde van het attribuut grondsoort gelijk is veen, zwakZandigVeen, matigzandigVeen, sterkZandigVeen, siltigVeen of kleiigVeen. In andere gevallen ontbreekt het gegeven._

Dit impliceert dat dit attribuut verplicht is in het geval van veen (plus evt. secundaire fractie). Echter, de eigenschap veensoort is in de laatste conceptversie van de NEN14688-1 volledig geschrapt. Derhalve dient dit attribuut in de BRO-catalogus óf geschrapt te worden óf optioneel te worden gemaakt indien de grondsoort gelijk is aan veen (plus evt. secundaire fractie).

**Comment by fterpstra** [comment]
in versie 0.9 opgelost
